/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.info.stel.leitorfebrabam.old;

/**
 *
 * @author p006184
 */
public class ResumoFatura extends javax.swing.JFrame {

    Fatura fatura;

    /**
     * Creates new form ResumoFatura
     */
    public ResumoFatura(Fatura fatura) {
        if (this.fatura == null) {
            this.fatura = new Fatura();
        }
        this.fatura = fatura;
        initComponents();
        populateForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitleFatura = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNumeroFatura = new javax.swing.JLabel();
        jLabelIdentificadorContaUnica = new javax.swing.JLabel();
        jLabelDataEmissao = new javax.swing.JLabel();
        jLabelMesReferencia = new javax.swing.JLabel();
        jLabelDataVencimento = new javax.swing.JLabel();
        jTextFieldIdentificadorContaUnica = new javax.swing.JTextField();
        jTextFieldNumeroFatura = new javax.swing.JTextField();
        jTextFieldDataEmissao = new javax.swing.JTextField();
        jTextFieldMesReferencia = new javax.swing.JTextField();
        jTextFieldDataVencimento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitleResumo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelValTotalChamadas = new javax.swing.JLabel();
        jTextFieldValTotalChamadas = new javax.swing.JTextField();
        jLabelValTotalServicos = new javax.swing.JLabel();
        jTextFieldValTotalServicos = new javax.swing.JTextField();
        jLabelValTotalImpostos = new javax.swing.JLabel();
        jTextFieldValTotalImpostos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitleBilhete = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelValTotalCalculadoComImpostoBilhete = new javax.swing.JLabel();
        jTextFieldValTotalCalculadoComImpostoBilhete = new javax.swing.JTextField();
        jLabelValTotalCalculadoSemImpostoBilhete = new javax.swing.JLabel();
        jTextFieldValTotalCalculadoSemImpostoBilhete = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitleServico = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelValTotalCalculadoComImpostoServico = new javax.swing.JLabel();
        jTextFieldValTotalCalculadoComImpostoServico = new javax.swing.JTextField();
        jLabelValTotalCalculadoSemImpostoServico = new javax.swing.JLabel();
        jTextFieldValTotalCalculadoSemImpostoServico = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabelTitleDescontos = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelValTotalDesconto = new javax.swing.JLabel();
        jTextFieldValTotalDesconto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleFatura.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabelTitleFatura.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitleFatura.setText("FATURA");

        jLabelNumeroFatura.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelNumeroFatura.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNumeroFatura.setText("Número:");

        jLabelIdentificadorContaUnica.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelIdentificadorContaUnica.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIdentificadorContaUnica.setText("Identificador de Conta Única:");

        jLabelDataEmissao.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelDataEmissao.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDataEmissao.setText("Data de emissão:");

        jLabelMesReferencia.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelMesReferencia.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMesReferencia.setText("Mês de referência:");

        jLabelDataVencimento.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelDataVencimento.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDataVencimento.setText("Data de Vencimento:");

        jTextFieldIdentificadorContaUnica.setEditable(false);
        jTextFieldIdentificadorContaUnica.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificadorContaUnica.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldIdentificadorContaUnica.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIdentificadorContaUnica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTextFieldNumeroFatura.setEditable(false);
        jTextFieldNumeroFatura.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumeroFatura.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldNumeroFatura.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNumeroFatura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTextFieldDataEmissao.setEditable(false);
        jTextFieldDataEmissao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataEmissao.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldDataEmissao.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDataEmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTextFieldMesReferencia.setEditable(false);
        jTextFieldMesReferencia.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMesReferencia.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldMesReferencia.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldMesReferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jTextFieldMesReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesReferenciaActionPerformed(evt);
            }
        });

        jTextFieldDataVencimento.setEditable(false);
        jTextFieldDataVencimento.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataVencimento.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldDataVencimento.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDataVencimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDataVencimento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIdentificadorContaUnica)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIdentificadorContaUnica, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDataEmissao)
                                    .addComponent(jLabelTitleFatura)
                                    .addComponent(jLabelNumeroFatura)
                                    .addComponent(jLabelMesReferencia)
                                    .addComponent(jTextFieldDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMesReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldNumeroFatura, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleFatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNumeroFatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIdentificadorContaUnica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIdentificadorContaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDataEmissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMesReferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMesReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDataVencimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleResumo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabelTitleResumo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitleResumo.setText("RESUMO");

        jLabelValTotalChamadas.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalChamadas.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalChamadas.setText("Valor Total de Chamadas:");

        jTextFieldValTotalChamadas.setEditable(false);
        jTextFieldValTotalChamadas.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalChamadas.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalChamadas.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalChamadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jTextFieldValTotalChamadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValTotalChamadasActionPerformed(evt);
            }
        });

        jLabelValTotalServicos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalServicos.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalServicos.setText("Valor Total de Serviços:");

        jTextFieldValTotalServicos.setEditable(false);
        jTextFieldValTotalServicos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalServicos.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalServicos.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalServicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jTextFieldValTotalServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValTotalServicosActionPerformed(evt);
            }
        });

        jLabelValTotalImpostos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalImpostos.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalImpostos.setText("Valor Total de Impostos:");

        jTextFieldValTotalImpostos.setEditable(false);
        jTextFieldValTotalImpostos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalImpostos.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalImpostos.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalImpostos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValTotalImpostos)
                            .addComponent(jTextFieldValTotalImpostos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTitleResumo)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelValTotalChamadas)
                                        .addComponent(jTextFieldValTotalChamadas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelValTotalServicos)
                                        .addComponent(jTextFieldValTotalServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelValTotalServicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValTotalServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTitleResumo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelValTotalChamadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValTotalChamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelValTotalImpostos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValTotalImpostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleBilhete.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabelTitleBilhete.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitleBilhete.setText("BILHETE");

        jLabelValTotalCalculadoComImpostoBilhete.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalCalculadoComImpostoBilhete.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalCalculadoComImpostoBilhete.setText("Valor Total com Impostos:");

        jTextFieldValTotalCalculadoComImpostoBilhete.setEditable(false);
        jTextFieldValTotalCalculadoComImpostoBilhete.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalCalculadoComImpostoBilhete.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalCalculadoComImpostoBilhete.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalCalculadoComImpostoBilhete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabelValTotalCalculadoSemImpostoBilhete.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalCalculadoSemImpostoBilhete.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalCalculadoSemImpostoBilhete.setText("Valor Total sem Impostos:");

        jTextFieldValTotalCalculadoSemImpostoBilhete.setEditable(false);
        jTextFieldValTotalCalculadoSemImpostoBilhete.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalCalculadoSemImpostoBilhete.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalCalculadoSemImpostoBilhete.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalCalculadoSemImpostoBilhete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTitleBilhete)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelValTotalCalculadoComImpostoBilhete)
                                .addComponent(jTextFieldValTotalCalculadoComImpostoBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelValTotalCalculadoSemImpostoBilhete)
                                .addComponent(jTextFieldValTotalCalculadoSemImpostoBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelValTotalCalculadoSemImpostoBilhete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValTotalCalculadoSemImpostoBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelTitleBilhete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelValTotalCalculadoComImpostoBilhete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValTotalCalculadoComImpostoBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleServico.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabelTitleServico.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitleServico.setText("SERVIÇO");

        jLabelValTotalCalculadoComImpostoServico.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalCalculadoComImpostoServico.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalCalculadoComImpostoServico.setText("Valor Total com Impostos:");

        jTextFieldValTotalCalculadoComImpostoServico.setEditable(false);
        jTextFieldValTotalCalculadoComImpostoServico.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalCalculadoComImpostoServico.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalCalculadoComImpostoServico.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalCalculadoComImpostoServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabelValTotalCalculadoSemImpostoServico.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalCalculadoSemImpostoServico.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalCalculadoSemImpostoServico.setText("Valor Total sem Impostos:");

        jTextFieldValTotalCalculadoSemImpostoServico.setEditable(false);
        jTextFieldValTotalCalculadoSemImpostoServico.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalCalculadoSemImpostoServico.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalCalculadoSemImpostoServico.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalCalculadoSemImpostoServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitleServico)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelValTotalCalculadoComImpostoServico)
                                    .addComponent(jTextFieldValTotalCalculadoComImpostoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelValTotalCalculadoSemImpostoServico)
                                    .addComponent(jTextFieldValTotalCalculadoSemImpostoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelValTotalCalculadoComImpostoServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValTotalCalculadoComImpostoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelValTotalCalculadoSemImpostoServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValTotalCalculadoSemImpostoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleDescontos.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabelTitleDescontos.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitleDescontos.setText("DESCONTOS");

        jLabelValTotalDesconto.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValTotalDesconto.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValTotalDesconto.setText("Valor Total com Impostos:");

        jTextFieldValTotalDesconto.setEditable(false);
        jTextFieldValTotalDesconto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValTotalDesconto.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldValTotalDesconto.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldValTotalDesconto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitleDescontos)
                            .addComponent(jLabelValTotalDesconto)
                            .addComponent(jTextFieldValTotalDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleDescontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelValTotalDesconto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValTotalDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMesReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMesReferenciaActionPerformed

    private void jTextFieldValTotalServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValTotalServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValTotalServicosActionPerformed

    private void jTextFieldValTotalChamadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValTotalChamadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValTotalChamadasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDataEmissao;
    private javax.swing.JLabel jLabelDataVencimento;
    private javax.swing.JLabel jLabelIdentificadorContaUnica;
    private javax.swing.JLabel jLabelMesReferencia;
    private javax.swing.JLabel jLabelNumeroFatura;
    private javax.swing.JLabel jLabelTitleBilhete;
    private javax.swing.JLabel jLabelTitleDescontos;
    private javax.swing.JLabel jLabelTitleFatura;
    private javax.swing.JLabel jLabelTitleResumo;
    private javax.swing.JLabel jLabelTitleServico;
    private javax.swing.JLabel jLabelValTotalCalculadoComImpostoBilhete;
    private javax.swing.JLabel jLabelValTotalCalculadoComImpostoServico;
    private javax.swing.JLabel jLabelValTotalCalculadoSemImpostoBilhete;
    private javax.swing.JLabel jLabelValTotalCalculadoSemImpostoServico;
    private javax.swing.JLabel jLabelValTotalChamadas;
    private javax.swing.JLabel jLabelValTotalDesconto;
    private javax.swing.JLabel jLabelValTotalImpostos;
    private javax.swing.JLabel jLabelValTotalServicos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldDataEmissao;
    private javax.swing.JTextField jTextFieldDataVencimento;
    private javax.swing.JTextField jTextFieldIdentificadorContaUnica;
    private javax.swing.JTextField jTextFieldMesReferencia;
    private javax.swing.JTextField jTextFieldNumeroFatura;
    private javax.swing.JTextField jTextFieldValTotalCalculadoComImpostoBilhete;
    private javax.swing.JTextField jTextFieldValTotalCalculadoComImpostoServico;
    private javax.swing.JTextField jTextFieldValTotalCalculadoSemImpostoBilhete;
    private javax.swing.JTextField jTextFieldValTotalCalculadoSemImpostoServico;
    private javax.swing.JTextField jTextFieldValTotalChamadas;
    private javax.swing.JTextField jTextFieldValTotalDesconto;
    private javax.swing.JTextField jTextFieldValTotalImpostos;
    private javax.swing.JTextField jTextFieldValTotalServicos;
    // End of variables declaration//GEN-END:variables

    private void populateForm() {
        jTextFieldNumeroFatura.setText(fatura.getNumeroFatura());
        jTextFieldDataEmissao.setText(fatura.getDataEmissao());
        jTextFieldDataVencimento.setText(fatura.getDataVencimento());
        jTextFieldMesReferencia.setText(fatura.getMesRefencia());
        jTextFieldIdentificadorContaUnica.setText(fatura.getIdentificadorContaUnica());
        
        jTextFieldValTotalChamadas.setText(fatura.getValTotalChamadasResumo().toString().replace('.', ','));
        jTextFieldValTotalServicos.setText(fatura.getValTotalServicosResumo().toString().replace('.', ','));
        jTextFieldValTotalImpostos.setText(fatura.getValTotalImpostosResumo().toString().replace('.', ','));
        
        jTextFieldValTotalCalculadoComImpostoBilhete.setText(fatura.getValTotalChamadasCalculadoComImposto().toString());
        jTextFieldValTotalCalculadoSemImpostoBilhete.setText(fatura.getValTotalChamadasCalculadoSemImposto().toString());
        
        jTextFieldValTotalCalculadoComImpostoServico.setText((fatura.getValTotalServicosCalculadoComImposto().toString()));
        jTextFieldValTotalCalculadoSemImpostoServico.setText(fatura.getValTotalServicosCalculadoSemImposto().toString());
        
        jTextFieldValTotalDesconto.setText(fatura.getValTotalDescontos().toString());
    }
}
