/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.info.stel.leitorfebrabam.old;

import br.info.stel.leitorfebrabam.old.FebrabamService;
import br.info.stel.leitorfebrabam.old.V3Service;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author p006184
 */
public class UploadFebrabam extends javax.swing.JFrame {

    /**
     * Creates new form UploadFebrabam
     */
    public UploadFebrabam() {
        initComponents();
    }

    private FileReader febrabamFile = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserFebrabam = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldFebramPath = new javax.swing.JTextField();
        jButtonOpen = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonRead = new javax.swing.JButton();
        jButtonShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldFebramPath.setEditable(false);
        jTextFieldFebramPath.setBackground(new java.awt.Color(255, 255, 255));

        jButtonOpen.setBackground(new java.awt.Color(0, 153, 255));
        jButtonOpen.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButtonOpen.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOpen.setText("Abrir");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 153, 255));
        jLabelTitle.setText("LEITOR FEBRABAM");

        jButtonRead.setBackground(new java.awt.Color(0, 153, 255));
        jButtonRead.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButtonRead.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRead.setText("Gravar");
        jButtonRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadActionPerformed(evt);
            }
        });

        jButtonShow.setBackground(new java.awt.Color(0, 153, 255));
        jButtonShow.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButtonShow.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShow.setText("Exibir");
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 142, Short.MAX_VALUE)
                                .addComponent(jLabelTitle))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonRead)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonShow)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFebramPath))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFebramPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRead)
                    .addComponent(jButtonShow))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
        jFileChooserFebrabam = new JFileChooser();
        int result = jFileChooserFebrabam.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {

            jTextFieldFebramPath.setText(jFileChooserFebrabam.getSelectedFile().getAbsolutePath());

        } else {
            System.out.println("Operação cancelada pelo usuário!");
        }
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadActionPerformed
        if (jTextFieldFebramPath != null) {
            try {
                febrabamFile = new FileReader(new File(jTextFieldFebramPath.getText()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(UploadFebrabam.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro ao gravar arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            FebrabamService febrabamService = new FebrabamService();

            String pathProcess = febrabamService.readFile(febrabamFile);
            if (pathProcess != null) {
                int input = JOptionPane.showConfirmDialog(null, "Arquivo gravado com SUCESSO no caminho: " + pathProcess + ". Deseja abrir a pasta?", "Mensagem", JOptionPane.YES_NO_OPTION);
                if (input == JOptionPane.YES_OPTION) {
                    Desktop desktop = Desktop.getDesktop();
                    File file = new File(pathProcess);
                    try {
                        desktop.open(file);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Não foi possível abrir a pasta!", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Erro na gravação do arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonReadActionPerformed

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        if (jTextFieldFebramPath != null) {
            try {
                febrabamFile = new FileReader(new File(jTextFieldFebramPath.getText()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(UploadFebrabam.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erro ao exibir fatura, tente abrir o arquivo novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            V3Service v3Service = new V3Service();
            Fatura fatura = new Fatura();

            boolean result = v3Service.readFile(febrabamFile, fatura);

            if (result) {
                new ResumoFatura(fatura).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao exibir fatura, tente abrir o arquivo novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonShowActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UploadFebrabam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UploadFebrabam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UploadFebrabam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UploadFebrabam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UploadFebrabam().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JFileChooser jFileChooserFebrabam;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldFebramPath;
    // End of variables declaration//GEN-END:variables
}
