/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tst.leitorfebrabam.view;

import br.com.tst.leitorfebrabam.model.EnderecoABV2;
import javax.swing.JFrame;

/**
 *
 * @author p006184
 */
public class EnderecoABV2Detail extends javax.swing.JFrame {
    private EnderecoABV2 enderecoABV2;
    /**
     * Creates new form EnderecoABV2Detail
     */
    public EnderecoABV2Detail(EnderecoABV2 enderecoABV2) {
        initComponents();
        this.enderecoABV2 = enderecoABV2;
        maximizeFrame();
        
        loadData();
    }

    public EnderecoABV2Detail() {
        initComponents();
        maximizeFrame();
        loadEmptyData();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabelTipoRegistro = new javax.swing.JLabel();
        jLabelControleSequencialGravacao = new javax.swing.JLabel();
        jLabelNumEnderecoPontaA = new javax.swing.JLabel();
        jLabelBairroPontaA = new javax.swing.JLabel();
        jLabelCnlRecursoEnderecoPontaA = new javax.swing.JLabel();
        jLabelIdentificadorUnicoRecurso = new javax.swing.JLabel();
        jLabelUfLocalidadePontaA = new javax.swing.JLabel();
        jLabelEnderecoPontaA = new javax.swing.JLabel();
        jLabelDdd = new javax.swing.JLabel();
        jLabelNumeroTelefone = new javax.swing.JLabel();
        jLabelComplementoPontaA = new javax.swing.JLabel();
        jLabelNomeLocalidadeEnderecoPontaA = new javax.swing.JLabel();
        jTextFieldControleSequencialGravacao = new javax.swing.JTextField();
        jTextFieldTipoRegistro = new javax.swing.JTextField();
        jTextFieldNumEnderecoPontaA = new javax.swing.JTextField();
        jTextFieldBairroPontaA = new javax.swing.JTextField();
        jTextFieldCnlRecursoEnderecoPontaA = new javax.swing.JTextField();
        jTextFieldUfLocalidadePontaA = new javax.swing.JTextField();
        jTextFieldIdentificadorUnicoRecurso = new javax.swing.JTextField();
        jTextFieldDdd = new javax.swing.JTextField();
        jTextFieldNumeroTelefone = new javax.swing.JTextField();
        jTextFieldComplementoPontaA = new javax.swing.JTextField();
        jTextFieldNomeLocalidadeEnderecoPontaA = new javax.swing.JTextField();
        jTextFieldUfLocalidadePontaB = new javax.swing.JTextField();
        jTextFieldEnderecoPontaA = new javax.swing.JTextField();
        jLabelCnlRecursoEnderecoPontaB = new javax.swing.JLabel();
        jTextFieldEnderecoPontaB = new javax.swing.JTextField();
        jLabelNomeLocalidadeEnderecoPontaB = new javax.swing.JLabel();
        jTextFieldNumEnderecoPontaB = new javax.swing.JTextField();
        jLabelUfLocalidadePontaB = new javax.swing.JLabel();
        jLabelEnderecoPontaB = new javax.swing.JLabel();
        jLabelNumEnderecoPontaB = new javax.swing.JLabel();
        jLabelCaracteristicaRecurso1 = new javax.swing.JLabel();
        jTextFieldCaracteristicaRecurso1 = new javax.swing.JTextField();
        jTextFieldCnlRecursoEnderecoPontaB = new javax.swing.JTextField();
        jTextFieldNomeLocalidadeEnderecoPontaB = new javax.swing.JTextField();
        jLabelComplementoPontaB = new javax.swing.JLabel();
        jLabelBairroPontaB = new javax.swing.JLabel();
        jTextFieldComplementoPontaB = new javax.swing.JTextField();
        jTextFieldBairroPontaB = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 102, 153));
        jLabelTitle.setText("Endereço das Pontas A e B");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jLabelTitle, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1200;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 6);
        jPanel1.add(jSeparator1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelTipoRegistro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelTipoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoRegistro.setText("Tipo de Registro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelTipoRegistro, gridBagConstraints);

        jLabelControleSequencialGravacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelControleSequencialGravacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelControleSequencialGravacao.setText("Controle Sequencial de Gravação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelControleSequencialGravacao, gridBagConstraints);

        jLabelNumEnderecoPontaA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNumEnderecoPontaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumEnderecoPontaA.setText("Nº do Endereço da Ponta A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNumEnderecoPontaA, gridBagConstraints);

        jLabelBairroPontaA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelBairroPontaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairroPontaA.setText("Bairro da Ponta A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelBairroPontaA, gridBagConstraints);

        jLabelCnlRecursoEnderecoPontaA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCnlRecursoEnderecoPontaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCnlRecursoEnderecoPontaA.setText("CNL do Recurso Endereço Ponta A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCnlRecursoEnderecoPontaA, gridBagConstraints);

        jLabelIdentificadorUnicoRecurso.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIdentificadorUnicoRecurso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdentificadorUnicoRecurso.setText("Identificador Único do Recurso (NRC)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelIdentificadorUnicoRecurso, gridBagConstraints);

        jLabelUfLocalidadePontaA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelUfLocalidadePontaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUfLocalidadePontaA.setText("UF da Localidade Ponta A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelUfLocalidadePontaA, gridBagConstraints);

        jLabelEnderecoPontaA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelEnderecoPontaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnderecoPontaA.setText("Endereço da Ponta A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelEnderecoPontaA, gridBagConstraints);

        jLabelDdd.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDdd.setText("DDD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelDdd, gridBagConstraints);

        jLabelNumeroTelefone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNumeroTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroTelefone.setText("Nº do Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNumeroTelefone, gridBagConstraints);

        jLabelComplementoPontaA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelComplementoPontaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComplementoPontaA.setText("Complemento da Ponta A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelComplementoPontaA, gridBagConstraints);

        jLabelNomeLocalidadeEnderecoPontaA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNomeLocalidadeEnderecoPontaA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeLocalidadeEnderecoPontaA.setText("Nome da Localidade do Endereço Ponta A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNomeLocalidadeEnderecoPontaA, gridBagConstraints);

        jTextFieldControleSequencialGravacao.setEditable(false);
        jTextFieldControleSequencialGravacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldControleSequencialGravacao.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldControleSequencialGravacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldControleSequencialGravacaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldControleSequencialGravacao, gridBagConstraints);

        jTextFieldTipoRegistro.setEditable(false);
        jTextFieldTipoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldTipoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoRegistroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldTipoRegistro, gridBagConstraints);

        jTextFieldNumEnderecoPontaA.setEditable(false);
        jTextFieldNumEnderecoPontaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumEnderecoPontaA.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNumEnderecoPontaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumEnderecoPontaAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNumEnderecoPontaA, gridBagConstraints);

        jTextFieldBairroPontaA.setEditable(false);
        jTextFieldBairroPontaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBairroPontaA.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldBairroPontaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroPontaAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldBairroPontaA, gridBagConstraints);

        jTextFieldCnlRecursoEnderecoPontaA.setEditable(false);
        jTextFieldCnlRecursoEnderecoPontaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCnlRecursoEnderecoPontaA.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCnlRecursoEnderecoPontaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnlRecursoEnderecoPontaAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCnlRecursoEnderecoPontaA, gridBagConstraints);

        jTextFieldUfLocalidadePontaA.setEditable(false);
        jTextFieldUfLocalidadePontaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUfLocalidadePontaA.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldUfLocalidadePontaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUfLocalidadePontaAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldUfLocalidadePontaA, gridBagConstraints);

        jTextFieldIdentificadorUnicoRecurso.setEditable(false);
        jTextFieldIdentificadorUnicoRecurso.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificadorUnicoRecurso.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIdentificadorUnicoRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificadorUnicoRecursoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldIdentificadorUnicoRecurso, gridBagConstraints);

        jTextFieldDdd.setEditable(false);
        jTextFieldDdd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDdd.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDdd, gridBagConstraints);

        jTextFieldNumeroTelefone.setEditable(false);
        jTextFieldNumeroTelefone.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumeroTelefone.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNumeroTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroTelefoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNumeroTelefone, gridBagConstraints);

        jTextFieldComplementoPontaA.setEditable(false);
        jTextFieldComplementoPontaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldComplementoPontaA.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldComplementoPontaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplementoPontaAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldComplementoPontaA, gridBagConstraints);

        jTextFieldNomeLocalidadeEnderecoPontaA.setEditable(false);
        jTextFieldNomeLocalidadeEnderecoPontaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeLocalidadeEnderecoPontaA.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNomeLocalidadeEnderecoPontaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeLocalidadeEnderecoPontaAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNomeLocalidadeEnderecoPontaA, gridBagConstraints);

        jTextFieldUfLocalidadePontaB.setEditable(false);
        jTextFieldUfLocalidadePontaB.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUfLocalidadePontaB.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldUfLocalidadePontaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUfLocalidadePontaBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldUfLocalidadePontaB, gridBagConstraints);

        jTextFieldEnderecoPontaA.setEditable(false);
        jTextFieldEnderecoPontaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEnderecoPontaA.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldEnderecoPontaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoPontaAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldEnderecoPontaA, gridBagConstraints);

        jLabelCnlRecursoEnderecoPontaB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCnlRecursoEnderecoPontaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCnlRecursoEnderecoPontaB.setText("CNL do Recurso Endereço Ponta B:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCnlRecursoEnderecoPontaB, gridBagConstraints);

        jTextFieldEnderecoPontaB.setEditable(false);
        jTextFieldEnderecoPontaB.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEnderecoPontaB.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldEnderecoPontaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoPontaBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 350, 0);
        jPanel2.add(jTextFieldEnderecoPontaB, gridBagConstraints);

        jLabelNomeLocalidadeEnderecoPontaB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNomeLocalidadeEnderecoPontaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeLocalidadeEnderecoPontaB.setText("Nome da Localidade do Endereço Ponta B:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNomeLocalidadeEnderecoPontaB, gridBagConstraints);

        jTextFieldNumEnderecoPontaB.setEditable(false);
        jTextFieldNumEnderecoPontaB.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumEnderecoPontaB.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNumEnderecoPontaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumEnderecoPontaBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 350, 0);
        jPanel2.add(jTextFieldNumEnderecoPontaB, gridBagConstraints);

        jLabelUfLocalidadePontaB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelUfLocalidadePontaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUfLocalidadePontaB.setText("UF da Localidade Ponta B:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelUfLocalidadePontaB, gridBagConstraints);

        jLabelEnderecoPontaB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelEnderecoPontaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnderecoPontaB.setText("Endereço da Ponta B:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelEnderecoPontaB, gridBagConstraints);

        jLabelNumEnderecoPontaB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNumEnderecoPontaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumEnderecoPontaB.setText("Nº do Endereço da Ponta B:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNumEnderecoPontaB, gridBagConstraints);

        jLabelCaracteristicaRecurso1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCaracteristicaRecurso1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCaracteristicaRecurso1.setText("Característica do Recurso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCaracteristicaRecurso1, gridBagConstraints);

        jTextFieldCaracteristicaRecurso1.setEditable(false);
        jTextFieldCaracteristicaRecurso1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCaracteristicaRecurso1.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCaracteristicaRecurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaracteristicaRecurso1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCaracteristicaRecurso1, gridBagConstraints);

        jTextFieldCnlRecursoEnderecoPontaB.setEditable(false);
        jTextFieldCnlRecursoEnderecoPontaB.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCnlRecursoEnderecoPontaB.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCnlRecursoEnderecoPontaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnlRecursoEnderecoPontaBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCnlRecursoEnderecoPontaB, gridBagConstraints);

        jTextFieldNomeLocalidadeEnderecoPontaB.setEditable(false);
        jTextFieldNomeLocalidadeEnderecoPontaB.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeLocalidadeEnderecoPontaB.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNomeLocalidadeEnderecoPontaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeLocalidadeEnderecoPontaBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNomeLocalidadeEnderecoPontaB, gridBagConstraints);

        jLabelComplementoPontaB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelComplementoPontaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComplementoPontaB.setText("Complemento da Ponta B:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelComplementoPontaB, gridBagConstraints);

        jLabelBairroPontaB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelBairroPontaB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairroPontaB.setText("Bairro da Ponta B:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelBairroPontaB, gridBagConstraints);

        jTextFieldComplementoPontaB.setEditable(false);
        jTextFieldComplementoPontaB.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldComplementoPontaB.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 350, 0);
        jPanel2.add(jTextFieldComplementoPontaB, gridBagConstraints);

        jTextFieldBairroPontaB.setEditable(false);
        jTextFieldBairroPontaB.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBairroPontaB.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 350, 0);
        jPanel2.add(jTextFieldBairroPontaB, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabelTitle1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle1.setForeground(new java.awt.Color(0, 153, 255));
        jLabelTitle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tst/leitorfebrabam/image/layout_set_logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Leitor Febrabam V1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelTitle1)
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldControleSequencialGravacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldControleSequencialGravacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldControleSequencialGravacaoActionPerformed

    private void jTextFieldTipoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoRegistroActionPerformed

    private void jTextFieldNumEnderecoPontaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumEnderecoPontaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumEnderecoPontaAActionPerformed

    private void jTextFieldBairroPontaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroPontaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroPontaAActionPerformed

    private void jTextFieldCnlRecursoEnderecoPontaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnlRecursoEnderecoPontaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnlRecursoEnderecoPontaAActionPerformed

    private void jTextFieldUfLocalidadePontaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUfLocalidadePontaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUfLocalidadePontaAActionPerformed

    private void jTextFieldIdentificadorUnicoRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificadorUnicoRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificadorUnicoRecursoActionPerformed

    private void jTextFieldDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDddActionPerformed

    private void jTextFieldNumeroTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroTelefoneActionPerformed

    private void jTextFieldComplementoPontaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplementoPontaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplementoPontaAActionPerformed

    private void jTextFieldNomeLocalidadeEnderecoPontaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeLocalidadeEnderecoPontaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeLocalidadeEnderecoPontaAActionPerformed

    private void jTextFieldUfLocalidadePontaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUfLocalidadePontaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUfLocalidadePontaBActionPerformed

    private void jTextFieldEnderecoPontaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoPontaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoPontaAActionPerformed

    private void jTextFieldEnderecoPontaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoPontaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoPontaBActionPerformed

    private void jTextFieldNumEnderecoPontaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumEnderecoPontaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumEnderecoPontaBActionPerformed

    private void jTextFieldCaracteristicaRecurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaracteristicaRecurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaracteristicaRecurso1ActionPerformed

    private void jTextFieldCnlRecursoEnderecoPontaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnlRecursoEnderecoPontaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnlRecursoEnderecoPontaBActionPerformed

    private void jTextFieldNomeLocalidadeEnderecoPontaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeLocalidadeEnderecoPontaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeLocalidadeEnderecoPontaBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBairroPontaA;
    private javax.swing.JLabel jLabelBairroPontaB;
    private javax.swing.JLabel jLabelCaracteristicaRecurso1;
    private javax.swing.JLabel jLabelCnlRecursoEnderecoPontaA;
    private javax.swing.JLabel jLabelCnlRecursoEnderecoPontaB;
    private javax.swing.JLabel jLabelComplementoPontaA;
    private javax.swing.JLabel jLabelComplementoPontaB;
    private javax.swing.JLabel jLabelControleSequencialGravacao;
    private javax.swing.JLabel jLabelDdd;
    private javax.swing.JLabel jLabelEnderecoPontaA;
    private javax.swing.JLabel jLabelEnderecoPontaB;
    private javax.swing.JLabel jLabelIdentificadorUnicoRecurso;
    private javax.swing.JLabel jLabelNomeLocalidadeEnderecoPontaA;
    private javax.swing.JLabel jLabelNomeLocalidadeEnderecoPontaB;
    private javax.swing.JLabel jLabelNumEnderecoPontaA;
    private javax.swing.JLabel jLabelNumEnderecoPontaB;
    private javax.swing.JLabel jLabelNumeroTelefone;
    private javax.swing.JLabel jLabelTipoRegistro;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelUfLocalidadePontaA;
    private javax.swing.JLabel jLabelUfLocalidadePontaB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBairroPontaA;
    private javax.swing.JTextField jTextFieldBairroPontaB;
    private javax.swing.JTextField jTextFieldCaracteristicaRecurso1;
    private javax.swing.JTextField jTextFieldCnlRecursoEnderecoPontaA;
    private javax.swing.JTextField jTextFieldCnlRecursoEnderecoPontaB;
    private javax.swing.JTextField jTextFieldComplementoPontaA;
    private javax.swing.JTextField jTextFieldComplementoPontaB;
    private javax.swing.JTextField jTextFieldControleSequencialGravacao;
    private javax.swing.JTextField jTextFieldDdd;
    private javax.swing.JTextField jTextFieldEnderecoPontaA;
    private javax.swing.JTextField jTextFieldEnderecoPontaB;
    private javax.swing.JTextField jTextFieldIdentificadorUnicoRecurso;
    private javax.swing.JTextField jTextFieldNomeLocalidadeEnderecoPontaA;
    private javax.swing.JTextField jTextFieldNomeLocalidadeEnderecoPontaB;
    private javax.swing.JTextField jTextFieldNumEnderecoPontaA;
    private javax.swing.JTextField jTextFieldNumEnderecoPontaB;
    private javax.swing.JTextField jTextFieldNumeroTelefone;
    private javax.swing.JTextField jTextFieldTipoRegistro;
    private javax.swing.JTextField jTextFieldUfLocalidadePontaA;
    private javax.swing.JTextField jTextFieldUfLocalidadePontaB;
    // End of variables declaration//GEN-END:variables
 private void maximizeFrame() {
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    private void loadData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void loadEmptyData() {
        jTextFieldTipoRegistro.setText("NÃO INFORMADO");
        jTextFieldControleSequencialGravacao.setText("NÃO INFORMADO");
        jTextFieldIdentificadorUnicoRecurso.setText("NÃO INFORMADO");
        jTextFieldDdd.setText("NÃO INFORMADO");
        jTextFieldNumeroTelefone.setText("NÃO INFORMADO");
        jTextFieldCaracteristicaRecurso1.setText("NÃO INFORMADO");
        jTextFieldCnlRecursoEnderecoPontaA.setText("NÃO INFORMADO");
        jTextFieldCnlRecursoEnderecoPontaB.setText("NÃO INFORMADO");
        jTextFieldNomeLocalidadeEnderecoPontaA.setText("NÃO INFORMADO");
        jTextFieldNomeLocalidadeEnderecoPontaB.setText("NÃO INFORMADO");
        jTextFieldUfLocalidadePontaA.setText("NÃO INFORMADO");
        jTextFieldUfLocalidadePontaB.setText("NÃO INFORMADO");
        jTextFieldEnderecoPontaA.setText("NÃO INFORMADO");
        jTextFieldEnderecoPontaB.setText("NÃO INFORMADO");
        jTextFieldNumEnderecoPontaA.setText("NÃO INFORMADO");
        jTextFieldNumEnderecoPontaB.setText("NÃO INFORMADO");
        jTextFieldComplementoPontaA.setText("NÃO INFORMADO");
        jTextFieldComplementoPontaB.setText("NÃO INFORMADO");
        jTextFieldBairroPontaA.setText("NÃO INFORMADO");
        jTextFieldBairroPontaB.setText("NÃO INFORMADO");
    }
}
