/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.tst.leitorfebrabam.view;

import br.com.tst.leitorfebrabam.model.V2;
import java.awt.GridLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author p006184
 */
public class FaturaV2_v2 extends javax.swing.JFrame {
    private V2 v2;
    /**
     * Creates new form FaturaV2_v2
     */
    public FaturaV2_v2(V2 v2) {
        initComponents();
        
        this.v2 = v2;
        
//        configTabbedPanel();        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelIdentificadorContaUnica = new javax.swing.JLabel();
        jTextFieldIdentificadorContaUnica = new javax.swing.JTextField();
        jLabelDataVencimento = new javax.swing.JLabel();
        jTextFieldDataVencimento = new javax.swing.JTextField();
        jLabelValorTotalChamadas = new javax.swing.JLabel();
        jTextFieldValorTotalChamadas = new javax.swing.JTextField();
        jLabelValorTotalServicos = new javax.swing.JLabel();
        jTextFieldValorTotalServicos = new javax.swing.JTextField();
        jLabelValorFatura = new javax.swing.JLabel();
        jTextFieldValorFatura = new javax.swing.JTextField();
        jLabelOperadora = new javax.swing.JLabel();
        jTextFieldOperadora = new javax.swing.JTextField();
        jLabelValorTotalChamadasServicos = new javax.swing.JLabel();
        jTextFieldValorTotalChamadasServicos = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHeader = new javax.swing.JPanel();
        jLabelUf = new javax.swing.JLabel();
        jTextFieldOperadoraHeader = new javax.swing.JTextField();
        jLabelTipoRegistro = new javax.swing.JLabel();
        jTextFieldTipoRegistro = new javax.swing.JTextField();
        jLabelControleSequencialGravacao = new javax.swing.JLabel();
        jTextFieldControleSequencialGravacao = new javax.swing.JTextField();
        jLabelDataGeracaoArquivo = new javax.swing.JLabel();
        jTextFieldDataGeracaoArquivo = new javax.swing.JTextField();
        jTextFieldUf = new javax.swing.JTextField();
        jLabelOperadoraHeader1 = new javax.swing.JLabel();
        jLabelOperadoraHeader2 = new javax.swing.JLabel();
        jTextFieldOperadoraHeader1 = new javax.swing.JTextField();
        jPanelResumo = new javax.swing.JPanel();
        jPanelChamadas = new javax.swing.JPanel();
        jPanelServicos = new javax.swing.JPanel();
        jPanelDesconto = new javax.swing.JPanel();
        jPanelTrailler = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FATURA V2");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));

        jLabelIdentificadorContaUnica.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelIdentificadorContaUnica.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIdentificadorContaUnica.setText("Identificador de conta única:");

        jTextFieldIdentificadorContaUnica.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificadorContaUnica.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldIdentificadorContaUnica.setForeground(new java.awt.Color(102, 102, 102));

        jLabelDataVencimento.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelDataVencimento.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDataVencimento.setText("Data de vencimento:");

        jTextFieldDataVencimento.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataVencimento.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldDataVencimento.setForeground(new java.awt.Color(102, 102, 102));

        jLabelValorTotalChamadas.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValorTotalChamadas.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValorTotalChamadas.setText("Valor total de chamadas:");

        jTextFieldValorTotalChamadas.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValorTotalChamadas.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldValorTotalChamadas.setForeground(new java.awt.Color(102, 102, 102));

        jLabelValorTotalServicos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValorTotalServicos.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValorTotalServicos.setText("Valor total de serviços:");

        jTextFieldValorTotalServicos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValorTotalServicos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldValorTotalServicos.setForeground(new java.awt.Color(102, 102, 102));

        jLabelValorFatura.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValorFatura.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValorFatura.setText("Valor da fatura:");

        jTextFieldValorFatura.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValorFatura.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldValorFatura.setForeground(new java.awt.Color(102, 102, 102));

        jLabelOperadora.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelOperadora.setForeground(new java.awt.Color(102, 102, 102));
        jLabelOperadora.setText("Operadora:");

        jTextFieldOperadora.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldOperadora.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldOperadora.setForeground(new java.awt.Color(102, 102, 102));

        jLabelValorTotalChamadasServicos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelValorTotalChamadasServicos.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValorTotalChamadasServicos.setText("Valor total de chamadas/serviço:");

        jTextFieldValorTotalChamadasServicos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValorTotalChamadasServicos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldValorTotalChamadasServicos.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIdentificadorContaUnica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldIdentificadorContaUnica)
                    .addComponent(jLabelDataVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDataVencimento)
                    .addComponent(jLabelValorTotalChamadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldValorTotalChamadas)
                    .addComponent(jLabelValorTotalServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldValorTotalServicos)
                    .addComponent(jLabelValorFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldValorFatura)
                    .addComponent(jLabelOperadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldOperadora)
                    .addComponent(jLabelValorTotalChamadasServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldValorTotalChamadasServicos))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIdentificadorContaUnica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIdentificadorContaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelOperadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDataVencimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorTotalChamadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorTotalChamadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorTotalServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorTotalServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorTotalChamadasServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorTotalChamadasServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorFatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabelUf.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelUf.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUf.setText("UF da Empresa Operadora:");

        jTextFieldOperadoraHeader.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldOperadoraHeader.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldOperadoraHeader.setForeground(new java.awt.Color(102, 102, 102));

        jLabelTipoRegistro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelTipoRegistro.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTipoRegistro.setText("Tipo de Registro:");

        jTextFieldTipoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipoRegistro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldTipoRegistro.setForeground(new java.awt.Color(102, 102, 102));

        jLabelControleSequencialGravacao.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelControleSequencialGravacao.setForeground(new java.awt.Color(102, 102, 102));
        jLabelControleSequencialGravacao.setText("Controle Sequencial de Gravação:");

        jTextFieldControleSequencialGravacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldControleSequencialGravacao.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldControleSequencialGravacao.setForeground(new java.awt.Color(102, 102, 102));

        jLabelDataGeracaoArquivo.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelDataGeracaoArquivo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDataGeracaoArquivo.setText("Data Geração do Arquivo:");

        jTextFieldDataGeracaoArquivo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataGeracaoArquivo.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldDataGeracaoArquivo.setForeground(new java.awt.Color(102, 102, 102));

        jTextFieldUf.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUf.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldUf.setForeground(new java.awt.Color(102, 102, 102));

        jLabelOperadoraHeader1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelOperadoraHeader1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelOperadoraHeader1.setText("Identificação da Empresa Operadora:");

        jLabelOperadoraHeader2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelOperadoraHeader2.setForeground(new java.awt.Color(102, 102, 102));
        jLabelOperadoraHeader2.setText("Identificação da Empresa Operadora:");

        jTextFieldOperadoraHeader1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldOperadoraHeader1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextFieldOperadoraHeader1.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoRegistro)
                    .addComponent(jTextFieldOperadoraHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelControleSequencialGravacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldControleSequencialGravacao))
                    .addComponent(jLabelDataGeracaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataGeracaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOperadoraHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addComponent(jLabelUf, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOperadoraHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOperadoraHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelTipoRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelControleSequencialGravacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldControleSequencialGravacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDataGeracaoArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataGeracaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelOperadoraHeader1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOperadoraHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelOperadoraHeader2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOperadoraHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HEADER", jPanelHeader);

        jPanelResumo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelResumoLayout = new javax.swing.GroupLayout(jPanelResumo);
        jPanelResumo.setLayout(jPanelResumoLayout);
        jPanelResumoLayout.setHorizontalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanelResumoLayout.setVerticalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("RESUMO", jPanelResumo);

        jPanelChamadas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelChamadasLayout = new javax.swing.GroupLayout(jPanelChamadas);
        jPanelChamadas.setLayout(jPanelChamadasLayout);
        jPanelChamadasLayout.setHorizontalGroup(
            jPanelChamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanelChamadasLayout.setVerticalGroup(
            jPanelChamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CHAMADAS", jPanelChamadas);

        jPanelServicos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelServicosLayout = new javax.swing.GroupLayout(jPanelServicos);
        jPanelServicos.setLayout(jPanelServicosLayout);
        jPanelServicosLayout.setHorizontalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanelServicosLayout.setVerticalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SERVIÇOS", jPanelServicos);

        jPanelDesconto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDescontoLayout = new javax.swing.GroupLayout(jPanelDesconto);
        jPanelDesconto.setLayout(jPanelDescontoLayout);
        jPanelDescontoLayout.setHorizontalGroup(
            jPanelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanelDescontoLayout.setVerticalGroup(
            jPanelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DESCONTOS", jPanelDesconto);

        jPanelTrailler.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTraillerLayout = new javax.swing.GroupLayout(jPanelTrailler);
        jPanelTrailler.setLayout(jPanelTraillerLayout);
        jPanelTraillerLayout.setHorizontalGroup(
            jPanelTraillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanelTraillerLayout.setVerticalGroup(
            jPanelTraillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("TRAILLER", jPanelTrailler);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelControleSequencialGravacao;
    private javax.swing.JLabel jLabelDataGeracaoArquivo;
    private javax.swing.JLabel jLabelDataVencimento;
    private javax.swing.JLabel jLabelIdentificadorContaUnica;
    private javax.swing.JLabel jLabelOperadora;
    private javax.swing.JLabel jLabelOperadoraHeader1;
    private javax.swing.JLabel jLabelOperadoraHeader2;
    private javax.swing.JLabel jLabelTipoRegistro;
    private javax.swing.JLabel jLabelUf;
    private javax.swing.JLabel jLabelValorFatura;
    private javax.swing.JLabel jLabelValorTotalChamadas;
    private javax.swing.JLabel jLabelValorTotalChamadasServicos;
    private javax.swing.JLabel jLabelValorTotalServicos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelChamadas;
    private javax.swing.JPanel jPanelDesconto;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelResumo;
    private javax.swing.JPanel jPanelServicos;
    private javax.swing.JPanel jPanelTrailler;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldControleSequencialGravacao;
    private javax.swing.JTextField jTextFieldDataGeracaoArquivo;
    private javax.swing.JTextField jTextFieldDataVencimento;
    private javax.swing.JTextField jTextFieldIdentificadorContaUnica;
    private javax.swing.JTextField jTextFieldOperadora;
    private javax.swing.JTextField jTextFieldOperadoraHeader;
    private javax.swing.JTextField jTextFieldOperadoraHeader1;
    private javax.swing.JTextField jTextFieldTipoRegistro;
    private javax.swing.JTextField jTextFieldUf;
    private javax.swing.JTextField jTextFieldValorFatura;
    private javax.swing.JTextField jTextFieldValorTotalChamadas;
    private javax.swing.JTextField jTextFieldValorTotalChamadasServicos;
    private javax.swing.JTextField jTextFieldValorTotalServicos;
    // End of variables declaration//GEN-END:variables

    private void configTabbedPanel() {
        JComponent panelHeader = createPanel();
        jTabbedPane1.addTab("HEADER", panelHeader);
    }

    private JComponent createPanel() {
        JPanel panel = new JPanel(false);        
        
        panel.setLayout(new GridLayout(1, 1));
        
        return panel;
    }
}
