/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tst.leitorfebrabam.view;

import br.com.tst.leitorfebrabam.model.EnderecoABV2;
import br.com.tst.leitorfebrabam.model.ResumoV2;
import br.com.tst.leitorfebrabam.model.V2;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author p006184
 */
public class FaturaV2 extends javax.swing.JFrame {

    private V2 v2;

    /**
     * Creates new form FaturaV2_v2
     */
    public FaturaV2(V2 v2) {
        initComponents();

        this.v2 = v2;

        maximizeFrame();
        configMenu();
        configHeaderPanel();
        configResumoPanel();
        configEnderecoPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelGray = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelIdentificadorContaUnica = new javax.swing.JLabel();
        jLabelValorTotalChamadas = new javax.swing.JLabel();
        jLabelValorTotalServicos = new javax.swing.JLabel();
        jLabelValorFatura = new javax.swing.JLabel();
        jLabelOperadora = new javax.swing.JLabel();
        jLabelIdentificadorContaUnicaValue = new javax.swing.JLabel();
        jLabelOperadoraValue = new javax.swing.JLabel();
        jLabelValorTotalChamadasValue = new javax.swing.JLabel();
        jLabelValorTotalServicosValue = new javax.swing.JLabel();
        jLabelValorFaturaValue = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHeader = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelUf = new javax.swing.JLabel();
        jTextFieldOperadoraHeader = new javax.swing.JTextField();
        jLabelTipoRegistro = new javax.swing.JLabel();
        jTextFieldTipoRegistro = new javax.swing.JTextField();
        jLabelControleSequencialGravacao = new javax.swing.JLabel();
        jTextFieldControleSequencialGravacao = new javax.swing.JTextField();
        jLabelDataGeracaoArquivo = new javax.swing.JLabel();
        jTextFieldDataGeracaoArquivo = new javax.swing.JTextField();
        jTextFieldUf = new javax.swing.JTextField();
        jLabelOperadoraHeader = new javax.swing.JLabel();
        jLabelCodigoCliente = new javax.swing.JLabel();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jTextFieldCgcCliente = new javax.swing.JTextField();
        jLabelCgcCliente = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldIdentificadorContaUnicaHeader = new javax.swing.JTextField();
        jLabelIdentificadorContaUnicaHeader = new javax.swing.JLabel();
        jTextFieldDataVencimentoHeader = new javax.swing.JTextField();
        jLabelDataVencimentoHeader = new javax.swing.JLabel();
        jLabelEmissao = new javax.swing.JLabel();
        jTextFieldEmissao = new javax.swing.JTextField();
        jPanelResumo = new javax.swing.JPanel();
        jScrollPanelResumoV2 = new javax.swing.JScrollPane();
        jTableResumoV2 = new javax.swing.JTable();
        jPanelEnderecos = new javax.swing.JPanel();
        jScrollPanelEnderecoV2 = new javax.swing.JScrollPane();
        jTableEnderecoV2 = new javax.swing.JTable();
        jPanelChamadas = new javax.swing.JPanel();
        jPanelServicos = new javax.swing.JPanel();
        jPanelDesconto = new javax.swing.JPanel();
        jPanelTrailler = new javax.swing.JPanel();
        jPanelBanner = new javax.swing.JPanel();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelGray.setBackground(new java.awt.Color(204, 204, 204));

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FATURA");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));

        jLabelIdentificadorContaUnica.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIdentificadorContaUnica.setForeground(new java.awt.Color(102, 102, 102));
        jLabelIdentificadorContaUnica.setText("Identificador de Conta única:");

        jLabelValorTotalChamadas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorTotalChamadas.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValorTotalChamadas.setText("Valor Total de Chamadas:");

        jLabelValorTotalServicos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorTotalServicos.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValorTotalServicos.setText("Valor Total de Serviços:");

        jLabelValorFatura.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorFatura.setForeground(new java.awt.Color(102, 102, 102));
        jLabelValorFatura.setText("Valor Total de Descontos:");

        jLabelOperadora.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelOperadora.setForeground(new java.awt.Color(102, 102, 102));
        jLabelOperadora.setText("Operadora:");

        jLabelIdentificadorContaUnicaValue.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIdentificadorContaUnicaValue.setForeground(new java.awt.Color(51, 51, 51));
        jLabelIdentificadorContaUnicaValue.setText("...");

        jLabelOperadoraValue.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelOperadoraValue.setForeground(new java.awt.Color(51, 51, 51));
        jLabelOperadoraValue.setText("...");

        jLabelValorTotalChamadasValue.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorTotalChamadasValue.setForeground(new java.awt.Color(51, 51, 51));
        jLabelValorTotalChamadasValue.setText("...");

        jLabelValorTotalServicosValue.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorTotalServicosValue.setForeground(new java.awt.Color(51, 51, 51));
        jLabelValorTotalServicosValue.setText("...");

        jLabelValorFaturaValue.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorFaturaValue.setForeground(new java.awt.Color(51, 51, 51));
        jLabelValorFaturaValue.setText("...");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIdentificadorContaUnica, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jLabelValorTotalChamadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelValorTotalServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelValorFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOperadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIdentificadorContaUnicaValue, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jLabelOperadoraValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelValorTotalChamadasValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelValorTotalServicosValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelValorFaturaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelIdentificadorContaUnica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIdentificadorContaUnicaValue)
                .addGap(18, 18, 18)
                .addComponent(jLabelOperadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOperadoraValue)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorTotalChamadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValorTotalChamadasValue)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorTotalServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValorTotalServicosValue)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorFatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValorFaturaValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(51, 153, 255));
        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanelHeaderLayout = new java.awt.GridBagLayout();
        jPanelHeaderLayout.columnWidths = new int[] {0};
        jPanelHeaderLayout.rowHeights = new int[] {0};
        jPanelHeader.setLayout(jPanelHeaderLayout);

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabelUf.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelUf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUf.setText("UF da Empresa Operadora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel5.add(jLabelUf, gridBagConstraints);

        jTextFieldOperadoraHeader.setEditable(false);
        jTextFieldOperadoraHeader.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldOperadoraHeader.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldOperadoraHeader.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldOperadoraHeader, gridBagConstraints);

        jLabelTipoRegistro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelTipoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoRegistro.setText("Tipo de Registro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 4, 0);
        jPanel5.add(jLabelTipoRegistro, gridBagConstraints);

        jTextFieldTipoRegistro.setEditable(false);
        jTextFieldTipoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipoRegistro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldTipoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldTipoRegistro, gridBagConstraints);

        jLabelControleSequencialGravacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelControleSequencialGravacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelControleSequencialGravacao.setText("Controle Sequencial de Gravação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel5.add(jLabelControleSequencialGravacao, gridBagConstraints);

        jTextFieldControleSequencialGravacao.setEditable(false);
        jTextFieldControleSequencialGravacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldControleSequencialGravacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldControleSequencialGravacao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldControleSequencialGravacao, gridBagConstraints);

        jLabelDataGeracaoArquivo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataGeracaoArquivo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataGeracaoArquivo.setText("Data Geração do Arquivo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelDataGeracaoArquivo, gridBagConstraints);

        jTextFieldDataGeracaoArquivo.setEditable(false);
        jTextFieldDataGeracaoArquivo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataGeracaoArquivo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldDataGeracaoArquivo.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 146;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldDataGeracaoArquivo, gridBagConstraints);

        jTextFieldUf.setEditable(false);
        jTextFieldUf.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUf.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldUf.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldUf, gridBagConstraints);

        jLabelOperadoraHeader.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelOperadoraHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOperadoraHeader.setText("Identificação da Empresa Operadora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelOperadoraHeader, gridBagConstraints);

        jLabelCodigoCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCodigoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoCliente.setText("Código do Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelCodigoCliente, gridBagConstraints);

        jTextFieldCodigoCliente.setEditable(false);
        jTextFieldCodigoCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldCodigoCliente.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldCodigoCliente, gridBagConstraints);

        jTextFieldCgcCliente.setEditable(false);
        jTextFieldCgcCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCgcCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldCgcCliente.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldCgcCliente, gridBagConstraints);

        jLabelCgcCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCgcCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCgcCliente.setText("CGC do Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelCgcCliente, gridBagConstraints);

        jLabelNomeCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeCliente.setText("Nome do Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelNomeCliente, gridBagConstraints);

        jTextFieldNomeCliente.setEditable(false);
        jTextFieldNomeCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldNomeCliente.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 430;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 300, 0);
        jPanel5.add(jTextFieldNomeCliente, gridBagConstraints);

        jTextFieldIdentificadorContaUnicaHeader.setEditable(false);
        jTextFieldIdentificadorContaUnicaHeader.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificadorContaUnicaHeader.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldIdentificadorContaUnicaHeader.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldIdentificadorContaUnicaHeader, gridBagConstraints);

        jLabelIdentificadorContaUnicaHeader.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIdentificadorContaUnicaHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdentificadorContaUnicaHeader.setText("Identificador Conta Única:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelIdentificadorContaUnicaHeader, gridBagConstraints);

        jTextFieldDataVencimentoHeader.setEditable(false);
        jTextFieldDataVencimentoHeader.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataVencimentoHeader.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldDataVencimentoHeader.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 146;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldDataVencimentoHeader, gridBagConstraints);

        jLabelDataVencimentoHeader.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataVencimentoHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataVencimentoHeader.setText("Data de Vencimento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelDataVencimentoHeader, gridBagConstraints);

        jLabelEmissao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelEmissao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmissao.setText("Data de Emissão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel5.add(jLabelEmissao, gridBagConstraints);

        jTextFieldEmissao.setEditable(false);
        jTextFieldEmissao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmissao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldEmissao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 146;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel5.add(jTextFieldEmissao, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 18, 50);
        jPanelHeader.add(jPanel5, gridBagConstraints);

        jTabbedPane1.addTab("HEADER", jPanelHeader);

        jPanelResumo.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPanelResumoV2.setBackground(new java.awt.Color(255, 255, 255));

        jTableResumoV2.setBackground(new java.awt.Color(255, 255, 255));
        jTableResumoV2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jTableResumoV2.setForeground(new java.awt.Color(51, 51, 51));
        jTableResumoV2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelResumoV2.setViewportView(jTableResumoV2);

        javax.swing.GroupLayout jPanelResumoLayout = new javax.swing.GroupLayout(jPanelResumo);
        jPanelResumo.setLayout(jPanelResumoLayout);
        jPanelResumoLayout.setHorizontalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelResumoV2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelResumoLayout.setVerticalGroup(
            jPanelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelResumoV2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("RESUMO", jPanelResumo);

        jPanelEnderecos.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPanelEnderecoV2.setBackground(new java.awt.Color(255, 255, 255));

        jTableEnderecoV2.setBackground(new java.awt.Color(255, 255, 255));
        jTableEnderecoV2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jTableEnderecoV2.setForeground(new java.awt.Color(51, 51, 51));
        jTableEnderecoV2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelEnderecoV2.setViewportView(jTableEnderecoV2);

        javax.swing.GroupLayout jPanelEnderecosLayout = new javax.swing.GroupLayout(jPanelEnderecos);
        jPanelEnderecos.setLayout(jPanelEnderecosLayout);
        jPanelEnderecosLayout.setHorizontalGroup(
            jPanelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelEnderecoV2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEnderecosLayout.setVerticalGroup(
            jPanelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanelEnderecoV2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ENDEREÇOS PONTA A E B", jPanelEnderecos);

        jPanelChamadas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelChamadasLayout = new javax.swing.GroupLayout(jPanelChamadas);
        jPanelChamadas.setLayout(jPanelChamadasLayout);
        jPanelChamadasLayout.setHorizontalGroup(
            jPanelChamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanelChamadasLayout.setVerticalGroup(
            jPanelChamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CHAMADAS", jPanelChamadas);

        jPanelServicos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelServicosLayout = new javax.swing.GroupLayout(jPanelServicos);
        jPanelServicos.setLayout(jPanelServicosLayout);
        jPanelServicosLayout.setHorizontalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanelServicosLayout.setVerticalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SERVIÇOS", jPanelServicos);

        jPanelDesconto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDescontoLayout = new javax.swing.GroupLayout(jPanelDesconto);
        jPanelDesconto.setLayout(jPanelDescontoLayout);
        jPanelDescontoLayout.setHorizontalGroup(
            jPanelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanelDescontoLayout.setVerticalGroup(
            jPanelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DESCONTOS", jPanelDesconto);

        jPanelTrailler.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTraillerLayout = new javax.swing.GroupLayout(jPanelTrailler);
        jPanelTrailler.setLayout(jPanelTraillerLayout);
        jPanelTraillerLayout.setHorizontalGroup(
            jPanelTraillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanelTraillerLayout.setVerticalGroup(
            jPanelTraillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("TRAILLER", jPanelTrailler);

        jPanelBanner.setBackground(new java.awt.Color(0, 102, 153));

        jLabelTitle2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle2.setForeground(new java.awt.Color(0, 153, 255));
        jLabelTitle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tst/leitorfebrabam/image/layout_set_logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Leitor Febrabam V1");

        javax.swing.GroupLayout jPanelBannerLayout = new javax.swing.GroupLayout(jPanelBanner);
        jPanelBanner.setLayout(jPanelBannerLayout);
        jPanelBannerLayout.setHorizontalGroup(
            jPanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBannerLayout.setVerticalGroup(
            jPanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBannerLayout.createSequentialGroup()
                .addComponent(jLabelTitle2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelGrayLayout = new javax.swing.GroupLayout(jPanelGray);
        jPanelGray.setLayout(jPanelGrayLayout);
        jPanelGrayLayout.setHorizontalGroup(
            jPanelGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanelBanner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGrayLayout.setVerticalGroup(
            jPanelGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrayLayout.createSequentialGroup()
                .addComponent(jPanelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCgcCliente;
    private javax.swing.JLabel jLabelCodigoCliente;
    private javax.swing.JLabel jLabelControleSequencialGravacao;
    private javax.swing.JLabel jLabelDataGeracaoArquivo;
    private javax.swing.JLabel jLabelDataVencimentoHeader;
    private javax.swing.JLabel jLabelEmissao;
    private javax.swing.JLabel jLabelIdentificadorContaUnica;
    private javax.swing.JLabel jLabelIdentificadorContaUnicaHeader;
    private javax.swing.JLabel jLabelIdentificadorContaUnicaValue;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelOperadora;
    private javax.swing.JLabel jLabelOperadoraHeader;
    private javax.swing.JLabel jLabelOperadoraValue;
    private javax.swing.JLabel jLabelTipoRegistro;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JLabel jLabelUf;
    private javax.swing.JLabel jLabelValorFatura;
    private javax.swing.JLabel jLabelValorFaturaValue;
    private javax.swing.JLabel jLabelValorTotalChamadas;
    private javax.swing.JLabel jLabelValorTotalChamadasValue;
    private javax.swing.JLabel jLabelValorTotalServicos;
    private javax.swing.JLabel jLabelValorTotalServicosValue;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBanner;
    private javax.swing.JPanel jPanelChamadas;
    private javax.swing.JPanel jPanelDesconto;
    private javax.swing.JPanel jPanelEnderecos;
    private javax.swing.JPanel jPanelGray;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelResumo;
    private javax.swing.JPanel jPanelServicos;
    private javax.swing.JPanel jPanelTrailler;
    private javax.swing.JScrollPane jScrollPanelEnderecoV2;
    private javax.swing.JScrollPane jScrollPanelResumoV2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEnderecoV2;
    private javax.swing.JTable jTableResumoV2;
    private javax.swing.JTextField jTextFieldCgcCliente;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldControleSequencialGravacao;
    private javax.swing.JTextField jTextFieldDataGeracaoArquivo;
    private javax.swing.JTextField jTextFieldDataVencimentoHeader;
    private javax.swing.JTextField jTextFieldEmissao;
    private javax.swing.JTextField jTextFieldIdentificadorContaUnicaHeader;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldOperadoraHeader;
    private javax.swing.JTextField jTextFieldTipoRegistro;
    private javax.swing.JTextField jTextFieldUf;
    // End of variables declaration//GEN-END:variables

    private void configMenu() {
        jLabelIdentificadorContaUnicaValue.setText(v2.getHeader().getIdentContaUnica());
        jLabelOperadoraValue.setText(v2.getHeader().getOperadora());
    }

    private void configHeaderPanel() {
        jTextFieldTipoRegistro.setText(v2.getHeader().getTipoRegistro());
        jTextFieldControleSequencialGravacao.setText(String.valueOf(v2.getHeader().getControleSeguencialGravacao()));
        jTextFieldDataGeracaoArquivo.setText(v2.getHeader().getDtaGeracaoArquivo());
        jTextFieldOperadoraHeader.setText(v2.getHeader().getOperadora());
        jTextFieldUf.setText(v2.getHeader().getUfOperadora());
        jTextFieldCodigoCliente.setText(v2.getHeader().getCodCliente());
        jTextFieldNomeCliente.setText(v2.getHeader().getNomCliente());
        jTextFieldCgcCliente.setText(v2.getHeader().getCgcCliente());
        jTextFieldIdentificadorContaUnicaHeader.setText(v2.getHeader().getIdentContaUnica());
        jTextFieldDataVencimentoHeader.setText(v2.getHeader().getDtaVencimento());
        jTextFieldEmissao.setText(v2.getHeader().getDtaEmissao());
    }

    private void configResumoPanel() {
        MyTableModel myTableModel = new MyTableModel(getResumoRowData(), getColumnNames("Controle Sequencial de Gravação", "Nº de Telefone", "Número da Nota Fiscal", "Valor da Conta"));
        jTableResumoV2.setModel(myTableModel);

        selectResumoListener();
    }

    private void configEnderecoPanel() {
        MyTableModel myTableModel = new MyTableModel(getEnderecoRowData(), getColumnNames("Controle Sequencial de Gravação", "Nº de Telefone"));
        jTableEnderecoV2.setModel(myTableModel);
        
        selectEnderecoListener();
    }

    private Vector<String> getColumnNames(String... params) {
        Vector<String> columnNames = new Vector<String>();

        for (String string : params) {

            columnNames.addElement(string);
        }

        return columnNames;
    }

    private Vector<Vector> getEnderecoRowData() {
        Vector<Vector> rowData = new Vector<>();

        if (v2.getEnderecosABV2() != null) {

            for (EnderecoABV2 enderecoABV2 : v2.getEnderecosABV2()) {
                Vector<String> row = new Vector<>();
                row.addElement(String.valueOf(enderecoABV2.getControleSequencialGravacao()));
                row.addElement(enderecoABV2.getNumTelefone());
                rowData.add(row);
            }
        } else {
            Vector<String> row = new Vector<>();
            row.addElement("NÃO INFORMADO");
            row.addElement("NÃO INFORMADO");
            rowData.add(row);
        }

        return rowData;
    }

    private Vector<Vector> getResumoRowData() {
        Vector<Vector> rowData = new Vector<>();

        for (ResumoV2 resumoV2 : v2.getResumosV2()) {
            Vector<String> row = new Vector<>();
            row.addElement(String.valueOf(resumoV2.getControleSequencialGravacao()));
            row.addElement(resumoV2.getNumTelefone());
            row.addElement(resumoV2.getNumNotaFiscal());
            row.addElement(resumoV2.getValConta().toString());
            rowData.add(row);
        }

        return rowData;
    }

    private void selectResumoListener() {
        jTableResumoV2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        ListSelectionModel lsm = jTableResumoV2.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    return;
                }

                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    int selectedRow = lsm.getMinSelectionIndex();
                    String controleSequencialSelected = (String) jTableResumoV2.getValueAt(selectedRow, 0);
                    showDetail(controleSequencialSelected);
                }
            }

            private void showDetail(String controleSequencialSelected) {
                int controleSequencialSearch = Integer.valueOf(controleSequencialSelected);
                ResumoV2 resumoV2 = new ResumoV2();
                for (ResumoV2 resumoV2Search : v2.getResumosV2()) {
                    if (resumoV2Search.getControleSequencialGravacao() == controleSequencialSearch) {
                        resumoV2 = resumoV2Search;
                    }
                }

                ResumoV2Detail resumoV2Detail = new ResumoV2Detail(resumoV2);
                resumoV2Detail.setVisible(true);

            }
        });
    }

    private void selectEnderecoListener() {
        jTableEnderecoV2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        ListSelectionModel lsm = jTableEnderecoV2.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    return;
                }

                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    if (v2.getEnderecosABV2() != null) {
                        int selectedRow = lsm.getMinSelectionIndex();
                        String controleSequencialSelected = (String) jTableEnderecoV2.getValueAt(selectedRow, 0);
                        showDetail(controleSequencialSelected);
                    }else{
                        showDetail();
                    }

                }
            }

            private void showDetail(String controleSequencialSelected) {
                
            }

            private void showDetail() {
                EnderecoABV2Detail eneEnderecoABV2Detail = new EnderecoABV2Detail();
                eneEnderecoABV2Detail.setVisible(true);
            }
        });
    }

    private void maximizeFrame() {
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

}
