/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.info.stel.leitorfebrabam.view.v2;

import br.info.stel.leitorfebrabam.model.v2.BilhetacaoV2;

import javax.swing.JFrame;

/**
 *
 * @author luis
 */
public class BilhetacaoV2Detail extends javax.swing.JFrame {

    private BilhetacaoV2 bilhetacaoV2;

    /**
     * Creates new form ResumoV2
     */
    public BilhetacaoV2Detail(BilhetacaoV2 bilhetacaoV2) {
        initComponents();
        this.bilhetacaoV2 = bilhetacaoV2;

        maximizeFrame();
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabelTipoRegistro = new javax.swing.JLabel();
        jLabelControleSequencialGravacao = new javax.swing.JLabel();
        jLabelClasseServico = new javax.swing.JLabel();
        jLabelDataVencimento = new javax.swing.JLabel();
        jLabelDataEmissao = new javax.swing.JLabel();
        jLabelIdentificadorUnicoRecurso = new javax.swing.JLabel();
        jLabelCnlRecursoReferencia = new javax.swing.JLabel();
        jLabelDdd = new javax.swing.JLabel();
        jLabelNumeroTelefone = new javax.swing.JLabel();
        jLabelDataLigacao = new javax.swing.JLabel();
        jLabelCnlLocalidadeChamada = new javax.swing.JLabel();
        jTextFieldControleSequencialGravacao = new javax.swing.JTextField();
        jTextFieldTipoRegistro = new javax.swing.JTextField();
        jTextFieldClasseServico = new javax.swing.JTextField();
        jTextFieldDataVencimento = new javax.swing.JTextField();
        jTextFieldDataEmissao = new javax.swing.JTextField();
        jTextFieldCnlRecursoReferencia = new javax.swing.JTextField();
        jTextFieldIdentificadorUnicoRecurso = new javax.swing.JTextField();
        jTextFieldDdd = new javax.swing.JTextField();
        jTextFieldNumeroTelefone = new javax.swing.JTextField();
        jTextFieldDataLigacao = new javax.swing.JTextField();
        jTextFieldCnlLocalidadeChamada = new javax.swing.JTextField();
        jTextFieldCodigoOperadora = new javax.swing.JTextField();
        jLabelDegrauRecurso = new javax.swing.JLabel();
        jTextFieldNomeLocalidadeChamada = new javax.swing.JTextField();
        jLabelCodigoNacionalInternacional = new javax.swing.JLabel();
        jTextFieldUfTelefoneChamado = new javax.swing.JTextField();
        jLabelCodigoOperadora = new javax.swing.JLabel();
        jLabelNomeLocalidadeChamada = new javax.swing.JLabel();
        jLabelUfTelefoneChamado = new javax.swing.JLabel();
        jLabelCaracteristicaRecurso1 = new javax.swing.JLabel();
        jTextFieldCaracteristicaRecurso1 = new javax.swing.JTextField();
        jTextFieldDegrauRecurso1 = new javax.swing.JTextField();
        jTextFieldCodigoNacionalInternacional = new javax.swing.JTextField();
        jLabelAreaDdd = new javax.swing.JLabel();
        jLabelNumeroTelefoneChamado = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldAreaDdd = new javax.swing.JTextField();
        jTextFieldNumeroTelefoneChamado = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jLabelDescricaoOperadora = new javax.swing.JLabel();
        jLabelCodigoPaisChamado = new javax.swing.JLabel();
        jLabelDescricaoCategoria = new javax.swing.JLabel();
        jTextFieldDescricaoOperadora = new javax.swing.JTextField();
        jTextFieldCodigoPaisChamado = new javax.swing.JTextField();
        jTextFieldDescricaoCategoria = new javax.swing.JTextField();
        jLabelConjugadoNumeroTelefoneChamado = new javax.swing.JLabel();
        jLabelDuracaoLigacao = new javax.swing.JLabel();
        jLabelGrupoHorarioTarifario = new javax.swing.JLabel();
        jTextFieldConjugadoNumeroTelefoneChamado = new javax.swing.JTextField();
        jTextFieldDuracaoLigacao = new javax.swing.JTextField();
        jTextFieldGrupoHorarioTarifario = new javax.swing.JTextField();
        jLabelDescricaoHorarioTarifario = new javax.swing.JLabel();
        jLabelHorarioLigacao = new javax.swing.JLabel();
        jLabelTipoChamada = new javax.swing.JLabel();
        jTextFieldDescricaoHorarioTarifario = new javax.swing.JTextField();
        jTextFieldHorarioLigacao = new javax.swing.JTextField();
        jTextFieldTipoChamada = new javax.swing.JTextField();
        jLabelAliquotaICMS = new javax.swing.JLabel();
        jLabelValorLigacaoImposto = new javax.swing.JLabel();
        jLabelDegrauLigacao = new javax.swing.JLabel();
        jTextFieldAliquotaICMS = new javax.swing.JTextField();
        jTextFieldValorLigacaoImposto = new javax.swing.JTextField();
        jTextFieldDegrauLigacao = new javax.swing.JTextField();
        jLabelSinalValorLigacao = new javax.swing.JLabel();
        jTextFieldSinalValorLigacao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 102, 153));
        jLabelTitle.setText("RESUMO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jLabelTitle, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1200;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 6);
        jPanel1.add(jSeparator1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelTipoRegistro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelTipoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoRegistro.setText("Tipo de Registro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelTipoRegistro, gridBagConstraints);

        jLabelControleSequencialGravacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelControleSequencialGravacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelControleSequencialGravacao.setText("Controle Sequencial de Gravação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelControleSequencialGravacao, gridBagConstraints);

        jLabelClasseServico.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelClasseServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClasseServico.setText("Classe de Serviço:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelClasseServico, gridBagConstraints);

        jLabelDataVencimento.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataVencimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataVencimento.setText("Data de Vencimento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDataVencimento, gridBagConstraints);

        jLabelDataEmissao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataEmissao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataEmissao.setText("Data de Emissão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDataEmissao, gridBagConstraints);

        jLabelIdentificadorUnicoRecurso.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIdentificadorUnicoRecurso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdentificadorUnicoRecurso.setText("Identificador Único do Recurso (NRC)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelIdentificadorUnicoRecurso, gridBagConstraints);

        jLabelCnlRecursoReferencia.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCnlRecursoReferencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCnlRecursoReferencia.setText("CNL do Recurso em Referência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCnlRecursoReferencia, gridBagConstraints);

        jLabelDdd.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDdd.setText("DDD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelDdd, gridBagConstraints);

        jLabelNumeroTelefone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNumeroTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroTelefone.setText("Nº do Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNumeroTelefone, gridBagConstraints);

        jLabelDataLigacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataLigacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataLigacao.setText("Data da Ligação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDataLigacao, gridBagConstraints);

        jLabelCnlLocalidadeChamada.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCnlLocalidadeChamada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCnlLocalidadeChamada.setText("CNL da Localidade Chamada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCnlLocalidadeChamada, gridBagConstraints);

        jTextFieldControleSequencialGravacao.setEditable(false);
        jTextFieldControleSequencialGravacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldControleSequencialGravacao.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldControleSequencialGravacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldControleSequencialGravacaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldControleSequencialGravacao, gridBagConstraints);

        jTextFieldTipoRegistro.setEditable(false);
        jTextFieldTipoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldTipoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoRegistroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldTipoRegistro, gridBagConstraints);

        jTextFieldClasseServico.setEditable(false);
        jTextFieldClasseServico.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldClasseServico.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldClasseServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClasseServicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 100, 0);
        jPanel2.add(jTextFieldClasseServico, gridBagConstraints);

        jTextFieldDataVencimento.setEditable(false);
        jTextFieldDataVencimento.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataVencimento.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataVencimentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDataVencimento, gridBagConstraints);

        jTextFieldDataEmissao.setEditable(false);
        jTextFieldDataEmissao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataEmissao.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDataEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataEmissaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDataEmissao, gridBagConstraints);

        jTextFieldCnlRecursoReferencia.setEditable(false);
        jTextFieldCnlRecursoReferencia.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCnlRecursoReferencia.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCnlRecursoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnlRecursoReferenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCnlRecursoReferencia, gridBagConstraints);

        jTextFieldIdentificadorUnicoRecurso.setEditable(false);
        jTextFieldIdentificadorUnicoRecurso.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificadorUnicoRecurso.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIdentificadorUnicoRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificadorUnicoRecursoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldIdentificadorUnicoRecurso, gridBagConstraints);

        jTextFieldDdd.setEditable(false);
        jTextFieldDdd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDdd.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDdd, gridBagConstraints);

        jTextFieldNumeroTelefone.setEditable(false);
        jTextFieldNumeroTelefone.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumeroTelefone.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNumeroTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroTelefoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNumeroTelefone, gridBagConstraints);

        jTextFieldDataLigacao.setEditable(false);
        jTextFieldDataLigacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataLigacao.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDataLigacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataLigacaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDataLigacao, gridBagConstraints);

        jTextFieldCnlLocalidadeChamada.setEditable(false);
        jTextFieldCnlLocalidadeChamada.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCnlLocalidadeChamada.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCnlLocalidadeChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnlLocalidadeChamadaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCnlLocalidadeChamada, gridBagConstraints);

        jTextFieldCodigoOperadora.setEditable(false);
        jTextFieldCodigoOperadora.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoOperadora.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCodigoOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoOperadoraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCodigoOperadora, gridBagConstraints);

        jLabelDegrauRecurso.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDegrauRecurso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrauRecurso.setText("Degrau do Recurso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDegrauRecurso, gridBagConstraints);

        jTextFieldNomeLocalidadeChamada.setEditable(false);
        jTextFieldNomeLocalidadeChamada.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeLocalidadeChamada.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNomeLocalidadeChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeLocalidadeChamadaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNomeLocalidadeChamada, gridBagConstraints);

        jLabelCodigoNacionalInternacional.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCodigoNacionalInternacional.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoNacionalInternacional.setText("Código Nacional/Internacional:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCodigoNacionalInternacional, gridBagConstraints);

        jTextFieldUfTelefoneChamado.setEditable(false);
        jTextFieldUfTelefoneChamado.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUfTelefoneChamado.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldUfTelefoneChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUfTelefoneChamadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldUfTelefoneChamado, gridBagConstraints);

        jLabelCodigoOperadora.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCodigoOperadora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoOperadora.setText("Código da Operadora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCodigoOperadora, gridBagConstraints);

        jLabelNomeLocalidadeChamada.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNomeLocalidadeChamada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeLocalidadeChamada.setText("Nome da Localidade Chamada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNomeLocalidadeChamada, gridBagConstraints);

        jLabelUfTelefoneChamado.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelUfTelefoneChamado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUfTelefoneChamado.setText("UF do Telefone Chamado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelUfTelefoneChamado, gridBagConstraints);

        jLabelCaracteristicaRecurso1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCaracteristicaRecurso1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCaracteristicaRecurso1.setText("Característica do Recurso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCaracteristicaRecurso1, gridBagConstraints);

        jTextFieldCaracteristicaRecurso1.setEditable(false);
        jTextFieldCaracteristicaRecurso1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCaracteristicaRecurso1.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCaracteristicaRecurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaracteristicaRecurso1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCaracteristicaRecurso1, gridBagConstraints);

        jTextFieldDegrauRecurso1.setEditable(false);
        jTextFieldDegrauRecurso1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDegrauRecurso1.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDegrauRecurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDegrauRecurso1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDegrauRecurso1, gridBagConstraints);

        jTextFieldCodigoNacionalInternacional.setEditable(false);
        jTextFieldCodigoNacionalInternacional.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoNacionalInternacional.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCodigoNacionalInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoNacionalInternacionalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCodigoNacionalInternacional, gridBagConstraints);

        jLabelAreaDdd.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelAreaDdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAreaDdd.setText("Área/DDD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelAreaDdd, gridBagConstraints);

        jLabelNumeroTelefoneChamado.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNumeroTelefoneChamado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroTelefoneChamado.setText("Número do Telefone Chamado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNumeroTelefoneChamado, gridBagConstraints);

        jLabelCategoria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setText("Categoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCategoria, gridBagConstraints);

        jTextFieldAreaDdd.setEditable(false);
        jTextFieldAreaDdd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAreaDdd.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldAreaDdd, gridBagConstraints);

        jTextFieldNumeroTelefoneChamado.setEditable(false);
        jTextFieldNumeroTelefoneChamado.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumeroTelefoneChamado.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNumeroTelefoneChamado, gridBagConstraints);

        jTextFieldCategoria.setEditable(false);
        jTextFieldCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCategoria.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCategoria, gridBagConstraints);

        jLabelDescricaoOperadora.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDescricaoOperadora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescricaoOperadora.setText("Descrição da Operadora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDescricaoOperadora, gridBagConstraints);

        jLabelCodigoPaisChamado.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCodigoPaisChamado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoPaisChamado.setText("Código do País Chamado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCodigoPaisChamado, gridBagConstraints);

        jLabelDescricaoCategoria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDescricaoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescricaoCategoria.setText("Descrição da Categoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDescricaoCategoria, gridBagConstraints);

        jTextFieldDescricaoOperadora.setEditable(false);
        jTextFieldDescricaoOperadora.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescricaoOperadora.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDescricaoOperadora, gridBagConstraints);

        jTextFieldCodigoPaisChamado.setEditable(false);
        jTextFieldCodigoPaisChamado.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoPaisChamado.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCodigoPaisChamado, gridBagConstraints);

        jTextFieldDescricaoCategoria.setEditable(false);
        jTextFieldDescricaoCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescricaoCategoria.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDescricaoCategoria, gridBagConstraints);

        jLabelConjugadoNumeroTelefoneChamado.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelConjugadoNumeroTelefoneChamado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConjugadoNumeroTelefoneChamado.setText("Conjugado do Número do Telefone Chamado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelConjugadoNumeroTelefoneChamado, gridBagConstraints);

        jLabelDuracaoLigacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDuracaoLigacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDuracaoLigacao.setText("Duração da Ligação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDuracaoLigacao, gridBagConstraints);

        jLabelGrupoHorarioTarifario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelGrupoHorarioTarifario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrupoHorarioTarifario.setText("Grupo Horário Tarifário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelGrupoHorarioTarifario, gridBagConstraints);

        jTextFieldConjugadoNumeroTelefoneChamado.setEditable(false);
        jTextFieldConjugadoNumeroTelefoneChamado.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldConjugadoNumeroTelefoneChamado.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldConjugadoNumeroTelefoneChamado, gridBagConstraints);

        jTextFieldDuracaoLigacao.setEditable(false);
        jTextFieldDuracaoLigacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDuracaoLigacao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDuracaoLigacao, gridBagConstraints);

        jTextFieldGrupoHorarioTarifario.setEditable(false);
        jTextFieldGrupoHorarioTarifario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldGrupoHorarioTarifario.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldGrupoHorarioTarifario, gridBagConstraints);

        jLabelDescricaoHorarioTarifario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDescricaoHorarioTarifario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescricaoHorarioTarifario.setText("Descrição do Horário Tarifário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDescricaoHorarioTarifario, gridBagConstraints);

        jLabelHorarioLigacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelHorarioLigacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHorarioLigacao.setText("Horário da Ligação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelHorarioLigacao, gridBagConstraints);

        jLabelTipoChamada.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelTipoChamada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoChamada.setText("Tipo de Chamada (TC):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelTipoChamada, gridBagConstraints);

        jTextFieldDescricaoHorarioTarifario.setEditable(false);
        jTextFieldDescricaoHorarioTarifario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescricaoHorarioTarifario.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDescricaoHorarioTarifario, gridBagConstraints);

        jTextFieldHorarioLigacao.setEditable(false);
        jTextFieldHorarioLigacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHorarioLigacao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldHorarioLigacao, gridBagConstraints);

        jTextFieldTipoChamada.setEditable(false);
        jTextFieldTipoChamada.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipoChamada.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldTipoChamada, gridBagConstraints);

        jLabelAliquotaICMS.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelAliquotaICMS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAliquotaICMS.setText("Alíquota ICMS:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelAliquotaICMS, gridBagConstraints);

        jLabelValorLigacaoImposto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorLigacaoImposto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorLigacaoImposto.setText("Valor da Ligação com Imposto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelValorLigacaoImposto, gridBagConstraints);

        jLabelDegrauLigacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDegrauLigacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrauLigacao.setText("Degrau da Ligação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDegrauLigacao, gridBagConstraints);

        jTextFieldAliquotaICMS.setEditable(false);
        jTextFieldAliquotaICMS.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAliquotaICMS.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldAliquotaICMS, gridBagConstraints);

        jTextFieldValorLigacaoImposto.setEditable(false);
        jTextFieldValorLigacaoImposto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValorLigacaoImposto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldValorLigacaoImposto, gridBagConstraints);

        jTextFieldDegrauLigacao.setEditable(false);
        jTextFieldDegrauLigacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDegrauLigacao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDegrauLigacao, gridBagConstraints);

        jLabelSinalValorLigacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelSinalValorLigacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSinalValorLigacao.setText("Sinal do Valor da Ligação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelSinalValorLigacao, gridBagConstraints);

        jTextFieldSinalValorLigacao.setEditable(false);
        jTextFieldSinalValorLigacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSinalValorLigacao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldSinalValorLigacao, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabelTitle1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle1.setForeground(new java.awt.Color(0, 153, 255));
        jLabelTitle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/info/stel/leitorfebrabam/image/layout_set_logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Leitor Febrabam V1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelTitle1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldControleSequencialGravacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldControleSequencialGravacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldControleSequencialGravacaoActionPerformed

    private void jTextFieldTipoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoRegistroActionPerformed

    private void jTextFieldClasseServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClasseServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClasseServicoActionPerformed

    private void jTextFieldDataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataVencimentoActionPerformed

    private void jTextFieldDataEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataEmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataEmissaoActionPerformed

    private void jTextFieldCnlRecursoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnlRecursoReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnlRecursoReferenciaActionPerformed

    private void jTextFieldIdentificadorUnicoRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificadorUnicoRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificadorUnicoRecursoActionPerformed

    private void jTextFieldDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDddActionPerformed

    private void jTextFieldNumeroTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroTelefoneActionPerformed

    private void jTextFieldDataLigacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataLigacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataLigacaoActionPerformed

    private void jTextFieldCnlLocalidadeChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnlLocalidadeChamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnlLocalidadeChamadaActionPerformed

    private void jTextFieldCodigoOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoOperadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoOperadoraActionPerformed

    private void jTextFieldNomeLocalidadeChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeLocalidadeChamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeLocalidadeChamadaActionPerformed

    private void jTextFieldUfTelefoneChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUfTelefoneChamadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUfTelefoneChamadoActionPerformed

    private void jTextFieldCaracteristicaRecurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaracteristicaRecurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaracteristicaRecurso1ActionPerformed

    private void jTextFieldDegrauRecurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDegrauRecurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDegrauRecurso1ActionPerformed

    private void jTextFieldCodigoNacionalInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoNacionalInternacionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoNacionalInternacionalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAliquotaICMS;
    private javax.swing.JLabel jLabelAreaDdd;
    private javax.swing.JLabel jLabelCaracteristicaRecurso1;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelClasseServico;
    private javax.swing.JLabel jLabelCnlLocalidadeChamada;
    private javax.swing.JLabel jLabelCnlRecursoReferencia;
    private javax.swing.JLabel jLabelCodigoNacionalInternacional;
    private javax.swing.JLabel jLabelCodigoOperadora;
    private javax.swing.JLabel jLabelCodigoPaisChamado;
    private javax.swing.JLabel jLabelConjugadoNumeroTelefoneChamado;
    private javax.swing.JLabel jLabelControleSequencialGravacao;
    private javax.swing.JLabel jLabelDataEmissao;
    private javax.swing.JLabel jLabelDataLigacao;
    private javax.swing.JLabel jLabelDataVencimento;
    private javax.swing.JLabel jLabelDdd;
    private javax.swing.JLabel jLabelDegrauLigacao;
    private javax.swing.JLabel jLabelDegrauRecurso;
    private javax.swing.JLabel jLabelDescricaoCategoria;
    private javax.swing.JLabel jLabelDescricaoHorarioTarifario;
    private javax.swing.JLabel jLabelDescricaoOperadora;
    private javax.swing.JLabel jLabelDuracaoLigacao;
    private javax.swing.JLabel jLabelGrupoHorarioTarifario;
    private javax.swing.JLabel jLabelHorarioLigacao;
    private javax.swing.JLabel jLabelIdentificadorUnicoRecurso;
    private javax.swing.JLabel jLabelNomeLocalidadeChamada;
    private javax.swing.JLabel jLabelNumeroTelefone;
    private javax.swing.JLabel jLabelNumeroTelefoneChamado;
    private javax.swing.JLabel jLabelSinalValorLigacao;
    private javax.swing.JLabel jLabelTipoChamada;
    private javax.swing.JLabel jLabelTipoRegistro;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelUfTelefoneChamado;
    private javax.swing.JLabel jLabelValorLigacaoImposto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAliquotaICMS;
    private javax.swing.JTextField jTextFieldAreaDdd;
    private javax.swing.JTextField jTextFieldCaracteristicaRecurso1;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldClasseServico;
    private javax.swing.JTextField jTextFieldCnlLocalidadeChamada;
    private javax.swing.JTextField jTextFieldCnlRecursoReferencia;
    private javax.swing.JTextField jTextFieldCodigoNacionalInternacional;
    private javax.swing.JTextField jTextFieldCodigoOperadora;
    private javax.swing.JTextField jTextFieldCodigoPaisChamado;
    private javax.swing.JTextField jTextFieldConjugadoNumeroTelefoneChamado;
    private javax.swing.JTextField jTextFieldControleSequencialGravacao;
    private javax.swing.JTextField jTextFieldDataEmissao;
    private javax.swing.JTextField jTextFieldDataLigacao;
    private javax.swing.JTextField jTextFieldDataVencimento;
    private javax.swing.JTextField jTextFieldDdd;
    private javax.swing.JTextField jTextFieldDegrauLigacao;
    private javax.swing.JTextField jTextFieldDegrauRecurso1;
    private javax.swing.JTextField jTextFieldDescricaoCategoria;
    private javax.swing.JTextField jTextFieldDescricaoHorarioTarifario;
    private javax.swing.JTextField jTextFieldDescricaoOperadora;
    private javax.swing.JTextField jTextFieldDuracaoLigacao;
    private javax.swing.JTextField jTextFieldGrupoHorarioTarifario;
    private javax.swing.JTextField jTextFieldHorarioLigacao;
    private javax.swing.JTextField jTextFieldIdentificadorUnicoRecurso;
    private javax.swing.JTextField jTextFieldNomeLocalidadeChamada;
    private javax.swing.JTextField jTextFieldNumeroTelefone;
    private javax.swing.JTextField jTextFieldNumeroTelefoneChamado;
    private javax.swing.JTextField jTextFieldSinalValorLigacao;
    private javax.swing.JTextField jTextFieldTipoChamada;
    private javax.swing.JTextField jTextFieldTipoRegistro;
    private javax.swing.JTextField jTextFieldUfTelefoneChamado;
    private javax.swing.JTextField jTextFieldValorLigacaoImposto;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        jTextFieldTipoRegistro.setText(bilhetacaoV2.getTipoRegistro());
        jTextFieldControleSequencialGravacao.setText(String.valueOf(bilhetacaoV2.getControleSequencialGravacao()));
        jTextFieldDataVencimento.setText(bilhetacaoV2.getDtaVencimento());
        jTextFieldDataEmissao.setText(bilhetacaoV2.getDtaEmissao());
        jTextFieldIdentificadorUnicoRecurso.setText(bilhetacaoV2.getIdentificadorUnicoRecurso());
        jTextFieldCnlRecursoReferencia.setText(String.valueOf(bilhetacaoV2.getCnlRecursoReferencia()));
        jTextFieldDdd.setText(bilhetacaoV2.getDdd());
        jTextFieldNumeroTelefone.setText(bilhetacaoV2.getNumTelefone());
        jTextFieldCaracteristicaRecurso1.setText(bilhetacaoV2.getCaracteristicaRecurso());
        jTextFieldDegrauRecurso1.setText(bilhetacaoV2.getDegrauRecurso());
        jTextFieldDataLigacao.setText(bilhetacaoV2.getDtaLigacao());
        jTextFieldCnlLocalidadeChamada.setText(String.valueOf(bilhetacaoV2.getCnlLocalidadeChamada()));
        jTextFieldNomeLocalidadeChamada.setText(bilhetacaoV2.getNomeLocalidadeChamada());
        jTextFieldUfTelefoneChamado.setText(bilhetacaoV2.getUfTelefoneChamado());
        jTextFieldCodigoNacionalInternacional.setText(bilhetacaoV2.getCodNacionalInternacional());
        jTextFieldCodigoOperadora.setText(bilhetacaoV2.getCodOperadora());
        jTextFieldDescricaoOperadora.setText(bilhetacaoV2.getDescOperadora());
        jTextFieldCodigoPaisChamado.setText(bilhetacaoV2.getCodPaisChamado());
        jTextFieldAreaDdd.setText(bilhetacaoV2.getAreaDdd());
        jTextFieldNumeroTelefoneChamado.setText(bilhetacaoV2.getNumTelefoneChamado());
        jTextFieldConjugadoNumeroTelefoneChamado.setText(bilhetacaoV2.getConjugadoNumeroTelefoneChamado());
        jTextFieldDuracaoLigacao.setText(bilhetacaoV2.getDuracaoLigacao());
        jTextFieldCategoria.setText(bilhetacaoV2.getCategoria());
        jTextFieldDescricaoCategoria.setText(bilhetacaoV2.getDescCategoria());
        jTextFieldHorarioLigacao.setText(bilhetacaoV2.getHorLigacao());
        jTextFieldTipoChamada.setText(bilhetacaoV2.getTipChamada());
        jTextFieldGrupoHorarioTarifario.setText(bilhetacaoV2.getGrupoHorTarifario());
        jTextFieldDescricaoHorarioTarifario.setText(bilhetacaoV2.getDescHorTarifario());
        jTextFieldDegrauLigacao.setText(String.valueOf(bilhetacaoV2.getDegrauLigacao()));
        jTextFieldSinalValorLigacao.setText(bilhetacaoV2.getSinalValLigacao());
        jTextFieldAliquotaICMS.setText(bilhetacaoV2.getAliquotaICMS());
        jTextFieldValorLigacaoImposto.setText(bilhetacaoV2.getValLigacaoComImposto().toString());
        jTextFieldClasseServico.setText(bilhetacaoV2.getClasseServico());
        
    }

    private void maximizeFrame() {
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
}
