/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.info.stel.leitorfebrabam.view.v2;

import br.info.stel.leitorfebrabam.model.v2.DescontoV2;
import br.info.stel.leitorfebrabam.model.v2.ServicoV2;

import javax.swing.JFrame;

/**
 *
 * @author luis
 */
public class DescontoV2Detail extends javax.swing.JFrame {

    private DescontoV2 descontoV2;

    /**
     * Creates new form ResumoV2
     */
    public DescontoV2Detail(DescontoV2 descontoV2) {
        initComponents();
        this.descontoV2 = descontoV2;

        maximizeFrame();
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabelTipoRegistro = new javax.swing.JLabel();
        jLabelControleSequencialGravacao = new javax.swing.JLabel();
        jLabelClasseServico = new javax.swing.JLabel();
        jLabelDataVencimento = new javax.swing.JLabel();
        jLabelDataEmissao = new javax.swing.JLabel();
        jLabelIdentificadorUnicoRecurso = new javax.swing.JLabel();
        jLabelCnlRecursoReferencia = new javax.swing.JLabel();
        jLabelDdd = new javax.swing.JLabel();
        jLabelNumeroTelefone = new javax.swing.JLabel();
        jTextFieldControleSequencialGravacao = new javax.swing.JTextField();
        jTextFieldTipoRegistro = new javax.swing.JTextField();
        jTextFieldClasseServico = new javax.swing.JTextField();
        jTextFieldDataVencimento = new javax.swing.JTextField();
        jTextFieldDataEmissao = new javax.swing.JTextField();
        jTextFieldCnlRecursoReferencia = new javax.swing.JTextField();
        jTextFieldIdentificadorUnicoRecurso = new javax.swing.JTextField();
        jTextFieldDdd = new javax.swing.JTextField();
        jTextFieldNumeroTelefone = new javax.swing.JTextField();
        jLabelDescGrupoCategoria = new javax.swing.JLabel();
        jTextFieldDescGrupoCategoria = new javax.swing.JTextField();
        jLabelGrupoCategoria = new javax.swing.JLabel();
        jTextFieldGrupoCategoria = new javax.swing.JTextField();
        jLabelValorLigacao = new javax.swing.JLabel();
        jTextFieldValorLigacao = new javax.swing.JTextField();
        jLabelIdentificadorContaUnica = new javax.swing.JLabel();
        jTextFieldIdentificadorContaUnica = new javax.swing.JTextField();
        jLabelSinalValorLigacao = new javax.swing.JLabel();
        jTextFieldSinalValorLigacao = new javax.swing.JTextField();
        jLabelBaseCalcDesconto = new javax.swing.JLabel();
        jTextFieldBaseCalcDesconto = new javax.swing.JTextField();
        jLabelPercentualDesconto = new javax.swing.JLabel();
        jTextFieldPercentualDesconto = new javax.swing.JTextField();
        jLabelDtaInicioAcerto = new javax.swing.JLabel();
        jTextFieldDtaInicioAcerto = new javax.swing.JTextField();
        jLabelHoraInicioAcerto = new javax.swing.JLabel();
        jTextFieldHoraInicioAcerto = new javax.swing.JTextField();
        jLabelDataFimAcerto = new javax.swing.JLabel();
        jTextFieldDataFimAcerto = new javax.swing.JTextField();
        jLabelHoraFimAcerto = new javax.swing.JLabel();
        jTextFieldHoraFimAcerto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 102, 153));
        jLabelTitle.setText("RESUMO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jLabelTitle, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1200;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 6);
        jPanel1.add(jSeparator1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelTipoRegistro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelTipoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoRegistro.setText("Tipo de Registro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelTipoRegistro, gridBagConstraints);

        jLabelControleSequencialGravacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelControleSequencialGravacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelControleSequencialGravacao.setText("Controle Sequencial de Gravação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelControleSequencialGravacao, gridBagConstraints);

        jLabelClasseServico.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelClasseServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClasseServico.setText("Classe de Serviço:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelClasseServico, gridBagConstraints);

        jLabelDataVencimento.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataVencimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataVencimento.setText("Data de Vencimento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelDataVencimento, gridBagConstraints);

        jLabelDataEmissao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataEmissao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataEmissao.setText("Data de Emissão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDataEmissao, gridBagConstraints);

        jLabelIdentificadorUnicoRecurso.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIdentificadorUnicoRecurso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdentificadorUnicoRecurso.setText("Identificador Único do Recurso (NRC):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelIdentificadorUnicoRecurso, gridBagConstraints);

        jLabelCnlRecursoReferencia.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelCnlRecursoReferencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCnlRecursoReferencia.setText("CNL do Recurso em Referência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelCnlRecursoReferencia, gridBagConstraints);

        jLabelDdd.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDdd.setText("DDD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelDdd, gridBagConstraints);

        jLabelNumeroTelefone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelNumeroTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroTelefone.setText("Nº do Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelNumeroTelefone, gridBagConstraints);

        jTextFieldControleSequencialGravacao.setEditable(false);
        jTextFieldControleSequencialGravacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldControleSequencialGravacao.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldControleSequencialGravacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldControleSequencialGravacaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldControleSequencialGravacao, gridBagConstraints);

        jTextFieldTipoRegistro.setEditable(false);
        jTextFieldTipoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipoRegistro.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldTipoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoRegistroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldTipoRegistro, gridBagConstraints);

        jTextFieldClasseServico.setEditable(false);
        jTextFieldClasseServico.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldClasseServico.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldClasseServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClasseServicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 100, 0);
        jPanel2.add(jTextFieldClasseServico, gridBagConstraints);

        jTextFieldDataVencimento.setEditable(false);
        jTextFieldDataVencimento.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataVencimento.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataVencimentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDataVencimento, gridBagConstraints);

        jTextFieldDataEmissao.setEditable(false);
        jTextFieldDataEmissao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataEmissao.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDataEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataEmissaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDataEmissao, gridBagConstraints);

        jTextFieldCnlRecursoReferencia.setEditable(false);
        jTextFieldCnlRecursoReferencia.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCnlRecursoReferencia.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCnlRecursoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnlRecursoReferenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldCnlRecursoReferencia, gridBagConstraints);

        jTextFieldIdentificadorUnicoRecurso.setEditable(false);
        jTextFieldIdentificadorUnicoRecurso.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificadorUnicoRecurso.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIdentificadorUnicoRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificadorUnicoRecursoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldIdentificadorUnicoRecurso, gridBagConstraints);

        jTextFieldDdd.setEditable(false);
        jTextFieldDdd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDdd.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDdd, gridBagConstraints);

        jTextFieldNumeroTelefone.setEditable(false);
        jTextFieldNumeroTelefone.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumeroTelefone.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNumeroTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroTelefoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldNumeroTelefone, gridBagConstraints);

        jLabelDescGrupoCategoria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDescGrupoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescGrupoCategoria.setText("Descrição do Grupo da Categoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDescGrupoCategoria, gridBagConstraints);

        jTextFieldDescGrupoCategoria.setEditable(false);
        jTextFieldDescGrupoCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescGrupoCategoria.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDescGrupoCategoria, gridBagConstraints);

        jLabelGrupoCategoria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelGrupoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrupoCategoria.setText("Grupo das Categorias:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelGrupoCategoria, gridBagConstraints);

        jTextFieldGrupoCategoria.setEditable(false);
        jTextFieldGrupoCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldGrupoCategoria.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldGrupoCategoria, gridBagConstraints);

        jLabelValorLigacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelValorLigacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorLigacao.setText("Valor da ligação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelValorLigacao, gridBagConstraints);

        jTextFieldValorLigacao.setEditable(false);
        jTextFieldValorLigacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValorLigacao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldValorLigacao, gridBagConstraints);

        jLabelIdentificadorContaUnica.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelIdentificadorContaUnica.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdentificadorContaUnica.setText("Identificador Conta Única:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel2.add(jLabelIdentificadorContaUnica, gridBagConstraints);

        jTextFieldIdentificadorContaUnica.setEditable(false);
        jTextFieldIdentificadorContaUnica.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdentificadorContaUnica.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIdentificadorContaUnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificadorContaUnicaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldIdentificadorContaUnica, gridBagConstraints);

        jLabelSinalValorLigacao.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelSinalValorLigacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSinalValorLigacao.setText("Sinal do Valor da Ligação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelSinalValorLigacao, gridBagConstraints);

        jTextFieldSinalValorLigacao.setEditable(false);
        jTextFieldSinalValorLigacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSinalValorLigacao.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldSinalValorLigacao, gridBagConstraints);

        jLabelBaseCalcDesconto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelBaseCalcDesconto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBaseCalcDesconto.setText("Base de Cálculo Desconto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelBaseCalcDesconto, gridBagConstraints);

        jTextFieldBaseCalcDesconto.setEditable(false);
        jTextFieldBaseCalcDesconto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBaseCalcDesconto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldBaseCalcDesconto, gridBagConstraints);

        jLabelPercentualDesconto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelPercentualDesconto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPercentualDesconto.setText("Percentual de Desconto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelPercentualDesconto, gridBagConstraints);

        jTextFieldPercentualDesconto.setEditable(false);
        jTextFieldPercentualDesconto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPercentualDesconto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldPercentualDesconto, gridBagConstraints);

        jLabelDtaInicioAcerto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDtaInicioAcerto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDtaInicioAcerto.setText("Data Ínicio do Acerto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDtaInicioAcerto, gridBagConstraints);

        jTextFieldDtaInicioAcerto.setEditable(false);
        jTextFieldDtaInicioAcerto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDtaInicioAcerto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDtaInicioAcerto, gridBagConstraints);

        jLabelHoraInicioAcerto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelHoraInicioAcerto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraInicioAcerto.setText("Hora Ínicio do Acerto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelHoraInicioAcerto, gridBagConstraints);

        jTextFieldHoraInicioAcerto.setEditable(false);
        jTextFieldHoraInicioAcerto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHoraInicioAcerto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldHoraInicioAcerto, gridBagConstraints);

        jLabelDataFimAcerto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelDataFimAcerto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataFimAcerto.setText("Data fim do Acerto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelDataFimAcerto, gridBagConstraints);

        jTextFieldDataFimAcerto.setEditable(false);
        jTextFieldDataFimAcerto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataFimAcerto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jTextFieldDataFimAcerto, gridBagConstraints);

        jLabelHoraFimAcerto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelHoraFimAcerto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraFimAcerto.setText("Hora Fim do Acerto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        jPanel2.add(jLabelHoraFimAcerto, gridBagConstraints);

        jTextFieldHoraFimAcerto.setEditable(false);
        jTextFieldHoraFimAcerto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHoraFimAcerto.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 100, 0);
        jPanel2.add(jTextFieldHoraFimAcerto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabelTitle1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle1.setForeground(new java.awt.Color(0, 153, 255));
        jLabelTitle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/info/stel/leitorfebrabam/image/layout_set_logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Leitor Febrabam V1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelTitle1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldControleSequencialGravacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldControleSequencialGravacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldControleSequencialGravacaoActionPerformed

    private void jTextFieldTipoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoRegistroActionPerformed

    private void jTextFieldClasseServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClasseServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClasseServicoActionPerformed

    private void jTextFieldDataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataVencimentoActionPerformed

    private void jTextFieldDataEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataEmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataEmissaoActionPerformed

    private void jTextFieldCnlRecursoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnlRecursoReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnlRecursoReferenciaActionPerformed

    private void jTextFieldIdentificadorUnicoRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificadorUnicoRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificadorUnicoRecursoActionPerformed

    private void jTextFieldDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDddActionPerformed

    private void jTextFieldNumeroTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroTelefoneActionPerformed

    private void jTextFieldIdentificadorContaUnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificadorContaUnicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificadorContaUnicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBaseCalcDesconto;
    private javax.swing.JLabel jLabelClasseServico;
    private javax.swing.JLabel jLabelCnlRecursoReferencia;
    private javax.swing.JLabel jLabelControleSequencialGravacao;
    private javax.swing.JLabel jLabelDataEmissao;
    private javax.swing.JLabel jLabelDataFimAcerto;
    private javax.swing.JLabel jLabelDataVencimento;
    private javax.swing.JLabel jLabelDdd;
    private javax.swing.JLabel jLabelDescGrupoCategoria;
    private javax.swing.JLabel jLabelDtaInicioAcerto;
    private javax.swing.JLabel jLabelGrupoCategoria;
    private javax.swing.JLabel jLabelHoraFimAcerto;
    private javax.swing.JLabel jLabelHoraInicioAcerto;
    private javax.swing.JLabel jLabelIdentificadorContaUnica;
    private javax.swing.JLabel jLabelIdentificadorUnicoRecurso;
    private javax.swing.JLabel jLabelNumeroTelefone;
    private javax.swing.JLabel jLabelPercentualDesconto;
    private javax.swing.JLabel jLabelSinalValorLigacao;
    private javax.swing.JLabel jLabelTipoRegistro;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelValorLigacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBaseCalcDesconto;
    private javax.swing.JTextField jTextFieldClasseServico;
    private javax.swing.JTextField jTextFieldCnlRecursoReferencia;
    private javax.swing.JTextField jTextFieldControleSequencialGravacao;
    private javax.swing.JTextField jTextFieldDataEmissao;
    private javax.swing.JTextField jTextFieldDataFimAcerto;
    private javax.swing.JTextField jTextFieldDataVencimento;
    private javax.swing.JTextField jTextFieldDdd;
    private javax.swing.JTextField jTextFieldDescGrupoCategoria;
    private javax.swing.JTextField jTextFieldDtaInicioAcerto;
    private javax.swing.JTextField jTextFieldGrupoCategoria;
    private javax.swing.JTextField jTextFieldHoraFimAcerto;
    private javax.swing.JTextField jTextFieldHoraInicioAcerto;
    private javax.swing.JTextField jTextFieldIdentificadorContaUnica;
    private javax.swing.JTextField jTextFieldIdentificadorUnicoRecurso;
    private javax.swing.JTextField jTextFieldNumeroTelefone;
    private javax.swing.JTextField jTextFieldPercentualDesconto;
    private javax.swing.JTextField jTextFieldSinalValorLigacao;
    private javax.swing.JTextField jTextFieldTipoRegistro;
    private javax.swing.JTextField jTextFieldValorLigacao;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        jTextFieldTipoRegistro.setText(descontoV2.getTipoRegistro());
        jTextFieldControleSequencialGravacao.setText(String.valueOf(descontoV2.getControleSequencialGravacao()));
        jTextFieldDataVencimento.setText(descontoV2.getDtaVencimento());
        jTextFieldDataEmissao.setText(descontoV2.getDtaEmissao());
        jTextFieldIdentificadorUnicoRecurso.setText(descontoV2.getIdentUnicoRecurso());
        jTextFieldIdentificadorContaUnica.setText(descontoV2.getIdentContaUnica());        
        jTextFieldCnlRecursoReferencia.setText(String.valueOf(descontoV2.getCnlRecursoReferencia()));
        jTextFieldDdd.setText(descontoV2.getDdd());
        jTextFieldNumeroTelefone.setText(descontoV2.getNumTelefone());              
        jTextFieldGrupoCategoria.setText(descontoV2.getGrupoCategoria());
        jTextFieldDescGrupoCategoria.setText(descontoV2.getDescGrupoCategoria());                        
        jTextFieldSinalValorLigacao.setText(descontoV2.getSinalValLigacao());        
        jTextFieldBaseCalcDesconto.setText(descontoV2.getBaseCalcDesconto());        
        jTextFieldPercentualDesconto.setText(descontoV2.getPercentualDesconto());                
        jTextFieldValorLigacao.setText(descontoV2.getValLigacao().toString());
        jTextFieldDtaInicioAcerto.setText(descontoV2.getDtaInicioAcerto());        
        jTextFieldHoraInicioAcerto.setText(descontoV2.getHorInicioAcerto());        
        jTextFieldDataFimAcerto.setText(descontoV2.getDtaFimAcerto());        
        jTextFieldHoraFimAcerto.setText(descontoV2.getHorFimAcerto());        
        jTextFieldClasseServico.setText(descontoV2.getClasseServico());        
    }

    private void maximizeFrame() {
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
}
